/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { ClientContactsResponseCommunicationMethodsItem } from './clientContactsResponseCommunicationMethodsItem';
import type { Address } from './address';

export interface ClientContactsResponse {
  /** Унікальний ідентифікатор (UUID v4) */
  id?: string;
  /** Номер телефону */
  phone?: string;
  /** Email адреса */
  email?: string;
  communicationMethods?: ClientContactsResponseCommunicationMethodsItem[];
  address?: Address;
}
