openapi: 3.0.3
info:
  title: Auth Domain API
  description: API для JWT автентифікації користувачів системи хімчистки
  version: 1.0.0
  contact:
    name: AKSI Development Team
    email: dev@aksi.com
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.aksi.com
    description: Production server
tags:
  - name: auth
    description: JWT автентифікація користувачів (логін, логаут, оновлення токенів)

paths:
  # Authentication
  /api/auth/login:
    $ref: "auth/paths/authentication.yaml#/~1api~1auth~1login"
  /api/auth/logout:
    $ref: "auth/paths/authentication.yaml#/~1api~1auth~1logout"
  /api/auth/refresh-token:
    $ref: "auth/paths/authentication.yaml#/~1api~1auth~1refresh-token"

components:
  schemas:
    # Request Schemas
    LoginRequest:
      $ref: "auth/schemas/auth-requests.yaml#/LoginRequest"
    RefreshTokenRequest:
      $ref: "auth/schemas/auth-requests.yaml#/RefreshTokenRequest"

    # Response Schemas
    AuthResponse:
      $ref: "auth/schemas/auth-responses.yaml#/AuthResponse"
    LogoutResponse:
      $ref: "auth/schemas/auth-responses.yaml#/LogoutResponse"

    # Enums
    TokenType:
      $ref: "auth/schemas/auth-enums.yaml#/TokenType"

    # Common Schemas (використовуємо спільні)
    ErrorResponse:
      $ref: "common/schemas/errors.yaml#/ErrorResponse"
    ValidationErrorResponse:
      $ref: "common/schemas/errors.yaml#/ValidationErrorResponse"
    FieldError:
      $ref: "common/schemas/errors.yaml#/FieldError"

  securitySchemes:
    BearerAuth:
      $ref: "common/security.yaml#/securitySchemes/BearerAuth"
    CookieAuth:
      $ref: "common/security.yaml#/securitySchemes/CookieAuth"

# Більшість endpoints потребують автентифікації, крім login
security:
  - CookieAuth: []
  - BearerAuth: []  # Legacy support
