openapi: 3.0.4
info:
  title: Branch Domain API
  description: API для управління філіями хімчистки
  version: 1.0.0
  contact:
    name: AKSI Development Team
    email: dev@aksi.com
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.aksi.com
    description: Production server
tags:
  - name: branches
    description: Управління філіями

paths:
  # Branch Management
  /api/branches:
    $ref: "branch/paths/branch-management.yaml#/~1api~1branches"
  /api/branches/{id}:
    $ref: "branch/paths/branch-management.yaml#/~1api~1branches~1{id}"

components:
  schemas:
    # Request Schemas
    CreateBranchRequest:
      $ref: "branch/schemas/branch-requests.yaml#/CreateBranchRequest"
    UpdateBranchRequest:
      $ref: "branch/schemas/branch-requests.yaml#/UpdateBranchRequest"
    WorkingScheduleRequest:
      $ref: "branch/schemas/branch-requests.yaml#/WorkingScheduleRequest"
    WorkingDayRequest:
      $ref: "branch/schemas/branch-requests.yaml#/WorkingDayRequest"

    # Response Schemas
    BranchResponse:
      $ref: "branch/schemas/branch-responses.yaml#/BranchResponse"
    BranchListResponse:
      $ref: "branch/schemas/branch-responses.yaml#/BranchListResponse"
    WorkingScheduleResponse:
      $ref: "branch/schemas/branch-responses.yaml#/WorkingScheduleResponse"
    WorkingDayResponse:
      $ref: "branch/schemas/branch-responses.yaml#/WorkingDayResponse"

    # Enums
    DayOfWeek:
      $ref: "branch/schemas/branch-enums.yaml#/DayOfWeek"

    # Common Schemas (використовуємо спільні)
    ErrorResponse:
      $ref: "common/schemas/errors.yaml#/ErrorResponse"
    ValidationErrorResponse:
      $ref: "common/schemas/errors.yaml#/ValidationErrorResponse"
    FieldError:
      $ref: "common/schemas/errors.yaml#/FieldError"
    Address:
      $ref: "common/schemas/address.yaml#/Address"

  securitySchemes:
    CookieAuth:
      $ref: "common/security.yaml#/securitySchemes/CookieAuth"

security:
  - CookieAuth: []