openapi: 3.0.4
info:
  title: Branch API
  description: Branch management API for dry cleaning locations
  version: 1.0.0
  contact:
    name: API Support
    email: support@dryclean.example.com

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.dryclean.example.com
    description: Production

tags:
  - name: branches
    description: Branch operations

paths:
  /api/branches:
    get:
      operationId: listBranches
      summary: List branches
      description: Get list of branches
      tags:
        - branches
      security:
        - cookieAuth: []
      parameters:
        - $ref: "../openapi/common.yaml#/components/parameters/PageNumber"
        - $ref: "../openapi/common.yaml#/components/parameters/PageSize"
        - $ref: "../openapi/common.yaml#/components/parameters/SortBy"
        - $ref: "../openapi/common.yaml#/components/parameters/SortOrder"
        - name: active
          in: query
          description: Filter by active status
          required: false
          schema:
            type: boolean
            default: true
        - name: search
          in: query
          description: Search by name or address
          required: false
          schema:
            type: string
      responses:
        "200":
          description: List of branches
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchListResponse"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"

    post:
      operationId: createBranch
      summary: Create new branch
      description: Create a new branch (admin only)
      tags:
        - branches
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBranchRequest"
      responses:
        "201":
          description: Branch created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchInfo"
        "400":
          $ref: "../openapi/common.yaml#/components/responses/BadRequest"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "403":
          $ref: "../openapi/common.yaml#/components/responses/Forbidden"
        "409":
          $ref: "../openapi/common.yaml#/components/responses/Conflict"

  /api/branches/active:
    get:
      operationId: getAllActiveBranches
      summary: Get all active branches
      description: Get all active branches for dropdowns (no pagination)
      tags:
        - branches
      security:
        - cookieAuth: []
      responses:
        "200":
          description: List of active branches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BranchInfo"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"

  /api/branches/{branchId}:
    parameters:
      - name: branchId
        in: path
        required: true
        description: Branch ID
        schema:
          type: string
          format: uuid

    get:
      operationId: getBranchById
      summary: Get branch details
      description: Get detailed branch information
      tags:
        - branches
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Branch details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchInfo"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"

    put:
      operationId: updateBranch
      summary: Update branch
      description: Update an existing branch (admin only)
      tags:
        - branches
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBranchRequest"
      responses:
        "200":
          description: Branch updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchInfo"
        "400":
          $ref: "../openapi/common.yaml#/components/responses/BadRequest"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "403":
          $ref: "../openapi/common.yaml#/components/responses/Forbidden"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"
        "409":
          $ref: "../openapi/common.yaml#/components/responses/Conflict"

    delete:
      operationId: deleteBranch
      summary: Delete branch
      description: Delete a branch (admin only)
      tags:
        - branches
      security:
        - cookieAuth: []
      responses:
        "204":
          description: Branch deleted successfully
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "403":
          $ref: "../openapi/common.yaml#/components/responses/Forbidden"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"

  /api/branches/{branchId}/activate:
    parameters:
      - name: branchId
        in: path
        required: true
        description: Branch ID
        schema:
          type: string
          format: uuid

    post:
      operationId: activateBranch
      summary: Activate branch
      description: Activate a deactivated branch (admin only)
      tags:
        - branches
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Branch activated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchInfo"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "403":
          $ref: "../openapi/common.yaml#/components/responses/Forbidden"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"
        "409":
          $ref: "../openapi/common.yaml#/components/responses/Conflict"

  /api/branches/{branchId}/deactivate:
    parameters:
      - name: branchId
        in: path
        required: true
        description: Branch ID
        schema:
          type: string
          format: uuid

    post:
      operationId: deactivateBranch
      summary: Deactivate branch
      description: Deactivate an active branch (admin only)
      tags:
        - branches
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Branch deactivated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchInfo"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "403":
          $ref: "../openapi/common.yaml#/components/responses/Forbidden"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"
        "409":
          $ref: "../openapi/common.yaml#/components/responses/Conflict"

components:
  # Use common responses from common.yaml instead of duplicating

  schemas:
    BranchInfo:
      type: object
      required:
        - id
        - name
        - address
        - phone
        - active
      properties:
        id:
          type: string
          format: uuid
          description: Branch ID
        name:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/UniqueName"
          description: Branch name
        address:
          type: string
          description: Branch address
        phone:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/PhoneNumber"
          description: Branch phone number
        email:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/Email"
          description: Branch email
        workingHours:
          type: string
          description: Working hours (e.g., "Пн-Пт 8:00-20:00, Сб 9:00-18:00")
        active:
          type: boolean
          description: Is branch active
        description:
          type: string
          description: Branch description
        sortOrder:
          type: integer
          description: Sort order for display
          default: 0
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp (UTC)
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp (UTC)

    CreateBranchRequest:
      type: object
      required:
        - name
        - address
        - phone
      properties:
        name:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/UniqueName"
          description: Branch name
        address:
          type: string
          minLength: 1
          maxLength: 500
          description: Branch address
        phone:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/PhoneNumber"
          description: Branch phone number
        email:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/Email"
          description: Branch email
        workingHours:
          type: string
          maxLength: 255
          description: Working hours
        active:
          type: boolean
          description: Is branch active
          default: true
        description:
          type: string
          maxLength: 1000
          description: Branch description
        sortOrder:
          type: integer
          description: Sort order for display
          default: 0

    UpdateBranchRequest:
      type: object
      properties:
        name:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/UniqueName"
          description: Branch name
        address:
          type: string
          minLength: 1
          maxLength: 500
          description: Branch address
        phone:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/PhoneNumber"
          description: Branch phone number
        email:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/Email"
          description: Branch email
        workingHours:
          type: string
          maxLength: 255
          description: Working hours
        active:
          type: boolean
          description: Is branch active
        description:
          type: string
          maxLength: 1000
          description: Branch description
        sortOrder:
          type: integer
          description: Sort order for display

    BranchListResponse:
      allOf:
        - $ref: "../openapi/common.yaml#/components/schemas/PaginatedResponse"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/BranchInfo"

    # ErrorResponse moved to common.yaml

  securitySchemes:
    cookieAuth:
      $ref: "../openapi/common.yaml#/components/securitySchemes/cookieAuth"
