openapi: 3.0.4
info:
  title: Cart API
  description: Shopping cart API for temporary order storage and price calculation
  version: 1.0.0
  contact:
    name: API Support
    email: support@dryclean.example.com

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.dryclean.example.com
    description: Production

tags:
  - name: cart
    description: Shopping cart operations

paths:
  /api/cart:
    get:
      operationId: getCart
      summary: Get current cart
      description: Get or create (getOrCreate) the active customer's shopping cart for this session
      tags:
        - cart
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Current cart details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartInfo"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"

    delete:
      operationId: clearCart
      summary: Clear cart
      description: Remove all items from the active customer's cart
      tags:
        - cart
      security:
        - cookieAuth: []
      responses:
        "204":
          description: Cart cleared successfully
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"

  /api/cart/items:
    post:
      operationId: addCartItem
      summary: Add item to cart
      description: Add a new item to the shopping cart
      tags:
        - cart
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddCartItemRequest"
      responses:
        "201":
          description: Item added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartItemInfo"
        "400":
          $ref: "../openapi/common.yaml#/components/responses/BadRequest"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"

  /api/cart/items/{itemId}:
    parameters:
      - name: itemId
        in: path
        required: true
        description: Cart item ID
        schema:
          type: string
          format: uuid

    put:
      operationId: updateCartItem
      summary: Update cart item
      description: Update quantity or characteristics of a cart item
      tags:
        - cart
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCartItemRequest"
      responses:
        "200":
          description: Item updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartItemInfo"
        "400":
          $ref: "../openapi/common.yaml#/components/responses/BadRequest"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"

    delete:
      operationId: removeCartItem
      summary: Remove item from cart
      description: Remove an item from the shopping cart
      tags:
        - cart
      security:
        - cookieAuth: []
      responses:
        "204":
          description: Item removed successfully
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"

  /api/cart/modifiers:
    put:
      operationId: updateCartModifiers
      summary: Update cart global modifiers
      description: Update global modifiers like urgency and discount
      tags:
        - cart
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCartModifiersRequest"
      responses:
        "200":
          description: Modifiers updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartInfo"
        "400":
          $ref: "../openapi/common.yaml#/components/responses/BadRequest"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"

  /api/cart/calculate:
    post:
      operationId: calculateCart
      summary: Calculate cart totals
      description: Recalculate all prices in the active customer's cart. Does not create a cart; returns 404 if no active cart exists for the session.
      tags:
        - cart
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Cart recalculated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartPricingInfo"
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"

  /api/cart/activate-customer:
    post:
      operationId: activateCustomerForCart
      summary: Activate customer for cart in current session
      description: Binds subsequent cart operations to the selected customer in this session
      tags:
        - cart
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActivateCustomerRequest"
      responses:
        "204":
          description: Customer activated for cart
        "401":
          $ref: "../openapi/common.yaml#/components/responses/Unauthorized"
        "404":
          $ref: "../openapi/common.yaml#/components/responses/NotFound"

components:
  schemas:
    ActivateCustomerRequest:
      type: object
      required:
        - customerId
      properties:
        customerId:
          type: string
          format: uuid
          description: Customer ID to activate
    CartInfo:
      type: object
      required:
        - id
        - customerId
        - items
        - pricing
        - createdAt
        - expiresAt
      properties:
        id:
          type: string
          format: uuid
          description: Cart ID
        customerId:
          type: string
          format: uuid
          description: Customer ID
        items:
          type: array
          items:
            $ref: "#/components/schemas/CartItemInfo"
          description: Cart items
        globalModifiers:
          $ref: "#/components/schemas/CartGlobalModifiers"
        pricing:
          $ref: "#/components/schemas/CartPricingInfo"
        createdAt:
          type: string
          format: date-time
          description: Cart creation time
        updatedAt:
          type: string
          format: date-time
          description: Last update time
        expiresAt:
          type: string
          format: date-time
          description: Cart expiration time (TTL)

    CartItemInfo:
      type: object
      required:
        - id
        - priceListItemId
        - priceListItem
        - quantity
        - characteristics
        - pricing
      properties:
        id:
          type: string
          format: uuid
          description: Cart item ID
        priceListItemId:
          type: string
          format: uuid
          description: Price list item ID
        priceListItem:
          $ref: "#/components/schemas/PriceListItemSummary"
        quantity:
          type: integer
          minimum: 1
          description: Quantity (in units)
        characteristics:
          $ref: "#/components/schemas/ItemCharacteristics"
        modifiers:
          type: array
          items:
            $ref: "#/components/schemas/ItemModifier"
          description: Applied modifiers
        pricing:
          $ref: "#/components/schemas/CartItemPricingInfo"

    PriceListItemSummary:
      type: object
      required:
        - id
        - name
        - categoryCode
        - unitOfMeasure
        - basePrice
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        categoryCode:
          $ref: "../openapi/common.yaml#/components/schemas/ServiceCategoryType"
        unitOfMeasure:
          $ref: "../openapi/common.yaml#/components/schemas/UnitOfMeasure"
        basePrice:
          type: integer
          description: Base price in kopiykas

    ItemCharacteristics:
      type: object
      properties:
        material:
          type: string
          description: Material type
        color:
          type: string
          description: Item color
        filler:
          type: string
          description: Filler type (for padded items)
        fillerCondition:
          $ref: "../openapi/common.yaml#/components/schemas/FillerCondition"
        wearLevel:
          $ref: "../openapi/common.yaml#/components/schemas/WearLevel"

    ItemModifier:
      type: object
      required:
        - code
        - name
        - type
        - value
      properties:
        code:
          type: string
          description: Modifier code
        name:
          type: string
          description: Modifier name
        type:
          $ref: "../openapi/common.yaml#/components/schemas/ModifierType"
        value:
          type: number
          description: Modifier value (percentage or fixed amount)

    CartGlobalModifiers:
      type: object
      properties:
        urgencyType:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/UrgencyType"
            - default: NORMAL
              description: Urgency type
        discountType:
          allOf:
            - $ref: "../openapi/common.yaml#/components/schemas/DiscountType"
            - default: NONE
              description: Discount type
        discountPercentage:
          type: integer
          minimum: 0
          maximum: 100
          description: Discount percentage (for OTHER type)
        expectedCompletionDate:
          type: string
          format: date-time
          description: Expected completion date
        expectedCompletionNote:
          type: string
          description: Optional note for expected completion (e.g., "після 14:00")

    CartItemPricingInfo:
      type: object
      required:
        - basePrice
        - modifiersTotalAmount
        - subtotal
        - urgencyAmount
        - discountAmount
        - total
      properties:
        basePrice:
          type: integer
          description: Base price in kopiykas
        modifierDetails:
          type: array
          items:
            $ref: "#/components/schemas/ModifierDetail"
          description: Applied modifier details
        modifiersTotalAmount:
          type: integer
          description: Total modifiers amount in kopiykas
        subtotal:
          type: integer
          description: Subtotal (base + modifiers) in kopiykas
        urgencyAmount:
          type: integer
          description: Urgency surcharge amount in kopiykas
        discountAmount:
          type: integer
          description: Discount amount in kopiykas
        total:
          type: integer
          description: Total price in kopiykas

    ModifierDetail:
      type: object
      required:
        - code
        - name
        - amount
      properties:
        code:
          type: string
        name:
          type: string
        amount:
          type: integer
          description: Modifier amount in kopiykas

    CartPricingInfo:
      type: object
      required:
        - itemsSubtotal
        - urgencyAmount
        - discountAmount
        - total
      properties:
        itemsSubtotal:
          type: integer
          description: Sum of all items subtotals in kopiykas
        urgencyAmount:
          type: integer
          description: Total urgency amount in kopiykas
        discountAmount:
          type: integer
          description: Total discount amount in kopiykas
        discountApplicableAmount:
          type: integer
          description: Amount eligible for discount in kopiykas
        total:
          type: integer
          description: Final total in kopiykas

    AddCartItemRequest:
      type: object
      required:
        - priceListItemId
        - quantity
      properties:
        priceListItemId:
          type: string
          format: uuid
          description: Price list item ID
        quantity:
          type: integer
          minimum: 1
          description: Quantity in smallest unit (piece=1; kilogram=grams)
        characteristics:
          $ref: "#/components/schemas/ItemCharacteristics"
        modifierCodes:
          type: array
          items:
            type: string
          description: Modifier codes to apply

    UpdateCartItemRequest:
      type: object
      properties:
        quantity:
          type: integer
          minimum: 1
          description: New quantity in smallest unit (piece=1; kilogram=grams)
        characteristics:
          $ref: "#/components/schemas/ItemCharacteristics"
        modifierCodes:
          type: array
          items:
            type: string
          description: Updated modifier codes

    UpdateCartModifiersRequest:
      type: object
      properties:
        urgencyType:
          $ref: "../openapi/common.yaml#/components/schemas/UrgencyType"
        discountType:
          $ref: "../openapi/common.yaml#/components/schemas/DiscountType"
        discountPercentage:
          type: integer
          minimum: 0
          maximum: 100
          description: Discount percentage (required for OTHER type)
        expectedCompletionDate:
          type: string
          format: date-time
          description: Expected completion date

    # ErrorResponse centralized in common.yaml

  securitySchemes:
    cookieAuth:
      $ref: "../openapi/common.yaml#/components/securitySchemes/cookieAuth"
