openapi: 3.0.3
info:
  title: Client Domain API
  description: API для управління клієнтами хімчистки
  version: 1.0.0
  contact:
    name: AKSI Development Team
    email: dev@aksi.com
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.aksi.com
    description: Production server
tags:
  - name: clients
    description: Управління клієнтами
  - name: client-search
    description: Пошук клієнтів
  - name: client-contacts
    description: Контактна інформація

paths:
  # Client Management
  /api/clients:
    $ref: "client/paths/client-management.yaml#/~1api~1clients"
  /api/clients/{id}:
    $ref: "client/paths/client-management.yaml#/~1api~1clients~1{id}"
  /api/clients/{id}/statistics:
    $ref: "client/paths/client-management.yaml#/~1api~1clients~1{id}~1statistics"

  # Client Search
  /api/clients/search:
    $ref: "client/paths/client-search.yaml#/~1api~1clients~1search"
  /api/clients/search/advanced:
    $ref: "client/paths/client-search.yaml#/~1api~1clients~1search~1advanced"

  # Client Contacts
  /api/clients/{id}/contacts:
    $ref: "client/paths/client-contacts.yaml#/~1api~1clients~1{id}~1contacts"

components:
  schemas:
    # Request Schemas
    CreateClientRequest:
      $ref: "client/schemas/client-requests.yaml#/CreateClientRequest"
    UpdateClientRequest:
      $ref: "client/schemas/client-requests.yaml#/UpdateClientRequest"
    ClientSearchRequest:
      $ref: "client/schemas/client-requests.yaml#/ClientSearchRequest"
    UpdateClientContactsRequest:
      $ref: "client/schemas/client-requests.yaml#/UpdateClientContactsRequest"

    # Response Schemas
    ClientResponse:
      $ref: "client/schemas/client-responses.yaml#/ClientResponse"
    ClientPageResponse:
      $ref: "client/schemas/client-responses.yaml#/ClientPageResponse"
    ClientSearchResponse:
      $ref: "client/schemas/client-responses.yaml#/ClientSearchResponse"
    ClientSearchResult:
      $ref: "client/schemas/client-responses.yaml#/ClientSearchResult"
    ClientContactsResponse:
      $ref: "client/schemas/client-responses.yaml#/ClientContactsResponse"
    ClientStatistics:
      $ref: "client/schemas/client-responses.yaml#/ClientStatistics"

    # Enums
    CommunicationMethod:
      $ref: "client/schemas/client-enums.yaml#/CommunicationMethod"
    ClientSourceType:
      $ref: "client/schemas/client-enums.yaml#/ClientSourceType"

    # Common Schemas (використовуємо спільні)
    Address:
      $ref: "common/schemas/address.yaml#/Address"
    CreateAddressRequest:
      $ref: "common/schemas/address.yaml#/CreateAddressRequest"
    UpdateAddressRequest:
      $ref: "common/schemas/address.yaml#/UpdateAddressRequest"
    ErrorResponse:
      $ref: "common/schemas/errors.yaml#/ErrorResponse"
    ValidationErrorResponse:
      $ref: "common/schemas/errors.yaml#/ValidationErrorResponse"
    FieldError:
      $ref: "common/schemas/errors.yaml#/FieldError"
    PageableInfo:
      $ref: "common/schemas/pagination.yaml#/PageableInfo"

  securitySchemes:
    BearerAuth:
      $ref: "common/security.yaml#/securitySchemes/BearerAuth"

security:
  - BearerAuth: []
