openapi: 3.0.3
info:
  title: Document Domain API
  description: API для управління документами в односторінковій системі хімчистки
  version: 1.0.0
  contact:
    name: AKSI Development Team
    email: dev@aksi.com
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.aksi.com
    description: Production server
tags:
  - name: receipts
    description: Управління квитанціями
  - name: documents
    description: Управління документами
  - name: digital-signatures
    description: Цифрові підписи
  - name: qr-codes
    description: QR-коди
  - name: pdf-generation
    description: Генерація PDF

paths:
  # Receipt Management
  /api/receipts:
    $ref: "document/paths/receipt-management.yaml#/~1api~1receipts"
  /api/receipts/{id}:
    $ref: "document/paths/receipt-management.yaml#/~1api~1receipts~1{id}"
  /api/receipts/{id}/print:
    $ref: "document/paths/receipt-management.yaml#/~1api~1receipts~1{id}~1print"
  /api/receipts/number/{receiptNumber}:
    $ref: "document/paths/receipt-management.yaml#/~1api~1receipts~1number~1{receiptNumber}"

  # PDF Generation
  /api/receipts/{id}/pdf:
    $ref: "document/paths/pdf-generation.yaml#/~1api~1receipts~1{id}~1pdf"

  # QR Code Management
  /api/qr-codes/generate:
    $ref: "document/paths/qr-code-management.yaml#/~1api~1qr-codes~1generate"
  /api/qr-codes/{id}:
    $ref: "document/paths/qr-code-management.yaml#/~1api~1qr-codes~1{id}"

  # Digital Signature Management
  /api/digital-signatures:
    $ref: "document/paths/digital-signature-management.yaml#/~1api~1digital-signatures"
  /api/digital-signatures/{id}:
    $ref: "document/paths/digital-signature-management.yaml#/~1api~1digital-signatures~1{id}"
  /api/digital-signatures/{id}/image:
    $ref: "document/paths/digital-signature-management.yaml#/~1api~1digital-signatures~1{id}~1image"
  /api/digital-signatures/{id}/validate:
    $ref: "document/paths/digital-signature-management.yaml#/~1api~1digital-signatures~1{id}~1validate"

  # Document Management
  /api/documents:
    $ref: "document/paths/document-management.yaml#/~1api~1documents"
  /api/documents/{id}:
    $ref: "document/paths/document-management.yaml#/~1api~1documents~1{id}"
  /api/documents/{id}/download:
    $ref: "document/paths/document-management.yaml#/~1api~1documents~1{id}~1download"
  /api/documents/{id}/status:
    $ref: "document/paths/document-management.yaml#/~1api~1documents~1{id}~1status"

components:
  schemas:
    # Request Schemas
    GenerateReceiptRequest:
      $ref: "document/schemas/document-requests.yaml#/GenerateReceiptRequest"
    UpdateReceiptRequest:
      $ref: "document/schemas/document-requests.yaml#/UpdateReceiptRequest"
    ReceiptDataRequest:
      $ref: "document/schemas/document-requests.yaml#/ReceiptDataRequest"
    CompanyInfoRequest:
      $ref: "document/schemas/document-requests.yaml#/CompanyInfoRequest"
    OperatorInfoRequest:
      $ref: "document/schemas/document-requests.yaml#/OperatorInfoRequest"
    LegalInfoRequest:
      $ref: "document/schemas/document-requests.yaml#/LegalInfoRequest"
    GenerateQRCodeRequest:
      $ref: "document/schemas/document-requests.yaml#/GenerateQRCodeRequest"
    CreateDigitalSignatureRequest:
      $ref: "document/schemas/document-requests.yaml#/CreateDigitalSignatureRequest"
    SignatureMetadataRequest:
      $ref: "document/schemas/document-requests.yaml#/SignatureMetadataRequest"
    GeneratePdfRequest:
      $ref: "document/schemas/document-requests.yaml#/GeneratePdfRequest"

    # Response Schemas
    ReceiptResponse:
      $ref: "document/schemas/document-responses.yaml#/ReceiptResponse"
    ReceiptDataResponse:
      $ref: "document/schemas/document-responses.yaml#/ReceiptDataResponse"
    CompanyInfoResponse:
      $ref: "document/schemas/document-responses.yaml#/CompanyInfoResponse"
    BranchInfoResponse:
      $ref: "document/schemas/document-responses.yaml#/BranchInfoResponse"
    OrderInfoResponse:
      $ref: "document/schemas/document-responses.yaml#/OrderInfoResponse"
    ClientInfoResponse:
      $ref: "document/schemas/document-responses.yaml#/ClientInfoResponse"
    ItemDetailResponse:
      $ref: "document/schemas/document-responses.yaml#/ItemDetailResponse"
    ModifierDetailResponse:
      $ref: "document/schemas/document-responses.yaml#/ModifierDetailResponse"
    PhotoSummaryResponse:
      $ref: "document/schemas/document-responses.yaml#/PhotoSummaryResponse"
    FinancialSummaryResponse:
      $ref: "document/schemas/document-responses.yaml#/FinancialSummaryResponse"
    LegalInfoResponse:
      $ref: "document/schemas/document-responses.yaml#/LegalInfoResponse"
    OperatorInfoResponse:
      $ref: "document/schemas/document-responses.yaml#/OperatorInfoResponse"
    DocumentResponse:
      $ref: "document/schemas/document-responses.yaml#/DocumentResponse"
    DocumentSummaryResponse:
      $ref: "document/schemas/document-responses.yaml#/DocumentSummaryResponse"
    DocumentMetadataResponse:
      $ref: "document/schemas/document-responses.yaml#/DocumentMetadataResponse"
    QRCodeResponse:
      $ref: "document/schemas/document-responses.yaml#/QRCodeResponse"
    QRCodeSummaryResponse:
      $ref: "document/schemas/document-responses.yaml#/QRCodeSummaryResponse"
    DigitalSignatureResponse:
      $ref: "document/schemas/document-responses.yaml#/DigitalSignatureResponse"
    DigitalSignatureSummaryResponse:
      $ref: "document/schemas/document-responses.yaml#/DigitalSignatureSummaryResponse"
    SignatureMetadataResponse:
      $ref: "document/schemas/document-responses.yaml#/SignatureMetadataResponse"
    ReceiptPageResponse:
      $ref: "document/schemas/document-responses.yaml#/ReceiptPageResponse"
    DocumentPageResponse:
      $ref: "document/schemas/document-responses.yaml#/DocumentPageResponse"

    # Enums
    DocumentType:
      $ref: "document/schemas/document-enums.yaml#/DocumentType"
    DocumentStatus:
      $ref: "document/schemas/document-enums.yaml#/DocumentStatus"
    SignatureType:
      $ref: "document/schemas/document-enums.yaml#/SignatureType"

    # Common Schemas (використовуємо спільні)
    ErrorResponse:
      $ref: "common/schemas/errors.yaml#/ErrorResponse"
    ValidationErrorResponse:
      $ref: "common/schemas/errors.yaml#/ValidationErrorResponse"
    FieldError:
      $ref: "common/schemas/errors.yaml#/FieldError"
    PageableInfo:
      $ref: "common/schemas/pagination.yaml#/PageableInfo"

  securitySchemes:
    CookieAuth:
      $ref: "common/security.yaml#/securitySchemes/CookieAuth"

security:
  - CookieAuth: []
