openapi: 3.0.3
info:
  title: Dry Cleaning Item Management API
  description: API для управління категоріями послуг, прайс-листом, модифікаторами цін та розрахунками
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: service-categories
    description: Категорії послуг
  - name: price-list
    description: Прайс-лист
  - name: price-modifiers
    description: Модифікатори цін

paths:
  # Service Categories
  /api/service-categories:
    $ref: "item/paths/service-categories.yaml#/~1api~1service-categories"
  # Price List
  /api/price-list:
    $ref: "item/paths/price-list.yaml#/~1api~1price-list"

  # Price Modifiers
  /api/price-modifiers:
    $ref: "item/paths/price-modifiers.yaml#/~1api~1price-modifiers"

components:
  schemas:
    # Response Schemas
    ServiceCategoryResponse:
      $ref: "item/schemas/item-responses.yaml#/ServiceCategoryResponse"
    PriceListItemResponse:
      $ref: "item/schemas/item-responses.yaml#/PriceListItemResponse"
    PriceModifierResponse:
      $ref: "item/schemas/item-responses.yaml#/PriceModifierResponse"
    PriceListResponse:
      $ref: "item/schemas/item-responses.yaml#/PriceListResponse"

    # Enums
    ItemColor:
      $ref: "item/schemas/item-enums.yaml#/ItemColor"
    ServiceCategory:
      $ref: "order/schemas/price-modifiers.yaml#/ServiceCategory"
    UnitType:
      $ref: "order/schemas/price-modifiers.yaml#/UnitType"
    ModifierType:
      $ref: "order/schemas/order-enums.yaml#/ModifierType"

    # Common Error Schemas
    ErrorResponse:
      $ref: "common/schemas/errors.yaml#/ErrorResponse"
    ValidationErrorResponse:
      $ref: "common/schemas/errors.yaml#/ValidationErrorResponse"
    FieldError:
      $ref: "common/schemas/errors.yaml#/FieldError"

    # Pagination
    PageableInfo:
      $ref: "common/schemas/pagination.yaml#/PageableInfo"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
