openapi: 3.0.4
info:
  title: Order Domain API
  description: API для управління замовленнями в односторінковій системі хімчистки
  version: 1.0.0
  contact:
    name: AKSI Development Team
    email: dev@aksi.com
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.aksi.com
    description: Production server
tags:
  - name: orders
    description: Управління замовленнями
  - name: order-items
    description: Управління предметами замовлення
  - name: order-calculations
    description: Розрахунки та калькулятор
  - name: order-completion
    description: Завершення замовлення

paths:
  # Order Management
  /api/orders:
    $ref: "order/paths/order-management.yaml#/~1api~1orders"
  /api/orders/{id}:
    $ref: "order/paths/order-management.yaml#/~1api~1orders~1{id}"
  /api/orders/{id}/payment:
    $ref: "order/paths/order-management.yaml#/~1api~1orders~1{id}~1payment"

  # Order Items
  /api/orders/{id}/items:
    $ref: "order/paths/order-items.yaml#/~1api~1orders~1{id}~1items"
  /api/orders/{orderId}/items/{itemId}:
    $ref: "order/paths/order-items.yaml#/~1api~1orders~1{orderId}~1items~1{itemId}"

  # Order Calculations
  /api/orders/{id}/calculate:
    $ref: "order/paths/order-calculations.yaml#/~1api~1orders~1{id}~1calculate"
  /api/orders/{id}/calculate/preview:
    $ref: "order/paths/order-calculations.yaml#/~1api~1orders~1{id}~1calculate~1preview"

  # Order Completion
  /api/orders/{id}/complete:
    $ref: "order/paths/order-completion.yaml#/~1api~1orders~1{id}~1complete"
  /api/orders/{id}/receipt:
    $ref: "order/paths/order-completion.yaml#/~1api~1orders~1{id}~1receipt"

components:
  schemas:
    # Request schemas
    CreateOrderRequest:
      $ref: "order/schemas/order-requests.yaml#/CreateOrderRequest"
    UpdateOrderRequest:
      $ref: "order/schemas/order-requests.yaml#/UpdateOrderRequest"
    DiscountRequest:
      $ref: "order/schemas/order-requests.yaml#/DiscountRequest"
    UpdatePaymentRequest:
      $ref: "order/schemas/order-requests.yaml#/UpdatePaymentRequest"
    CompleteOrderRequest:
      $ref: "order/schemas/order-requests.yaml#/CompleteOrderRequest"

    # Order Item schemas
    CreateOrderItemRequest:
      $ref: "order/schemas/order-item-schemas.yaml#/CreateOrderItemRequest"
    UpdateOrderItemRequest:
      $ref: "order/schemas/order-item-schemas.yaml#/UpdateOrderItemRequest"
    PriceModifierRequest:
      $ref: "order/schemas/order-item-schemas.yaml#/PriceModifierRequest"
    StainType:
      $ref: "order/schemas/order-enums.yaml#/StainType"
    DefectType:
      $ref: "order/schemas/order-enums.yaml#/DefectType"

    # Response schemas
    OrderResponse:
      $ref: "order/schemas/order-responses.yaml#/OrderResponse"
    OrderListResponse:
      $ref: "order/schemas/order-responses.yaml#/OrderListResponse"
    OrderItemResponse:
      $ref: "order/schemas/order-responses.yaml#/OrderItemResponse"
    ClientSummary:
      $ref: "order/schemas/order-responses.yaml#/ClientSummary"
    BranchSummary:
      $ref: "order/schemas/order-responses.yaml#/BranchSummary"
    OrderCalculationSummary:
      $ref: "order/schemas/order-responses.yaml#/OrderCalculationSummary"
    DiscountInfo:
      $ref: "order/schemas/order-responses.yaml#/DiscountInfo"
    PaymentInfo:
      $ref: "order/schemas/order-responses.yaml#/PaymentInfo"
    AppliedModifier:
      $ref: "order/schemas/order-responses.yaml#/AppliedModifier"
    ItemCalculationDetails:
      $ref: "order/schemas/order-responses.yaml#/ItemCalculationDetails"
    CalculationStep:
      $ref: "order/schemas/order-responses.yaml#/CalculationStep"

    # Calculation schemas
    CalculateOrderRequest:
      $ref: "order/schemas/order-calculation-schemas.yaml#/CalculateOrderRequest"
    OrderCalculationResponse:
      $ref: "order/schemas/order-calculation-schemas.yaml#/OrderCalculationResponse"
    CompletedOrderResponse:
      $ref: "order/schemas/order-calculation-schemas.yaml#/CompletedOrderResponse"

    # Enum schemas
    OrderStatus:
      $ref: "order/schemas/order-enums.yaml#/OrderStatus"
    UrgencyType:
      $ref: "order/schemas/order-enums.yaml#/UrgencyType"
    DiscountType:
      $ref: "order/schemas/order-enums.yaml#/DiscountType"
    PaymentMethod:
      $ref: "order/schemas/order-enums.yaml#/PaymentMethod"
    ModifierType:
      $ref: "order/schemas/order-enums.yaml#/ModifierType"

    # Price modifiers (moved from separate file)
    GeneralModifiers:
      $ref: "order/schemas/price-modifiers.yaml#/GeneralModifiers"
    TextileModifiers:
      $ref: "order/schemas/price-modifiers.yaml#/TextileModifiers"
    LeatherModifiers:
      $ref: "order/schemas/price-modifiers.yaml#/LeatherModifiers"
    ServiceCategory:
      $ref: "order/schemas/price-modifiers.yaml#/ServiceCategory"
    MaterialType:
      $ref: "order/schemas/price-modifiers.yaml#/MaterialType"
    FillingType:
      $ref: "order/schemas/price-modifiers.yaml#/FillingType"
    UnitType:
      $ref: "order/schemas/price-modifiers.yaml#/UnitType"

    # Common schemas
    ErrorResponse:
      $ref: "common/schemas/errors.yaml#/ErrorResponse"
    ValidationErrorResponse:
      $ref: "common/schemas/errors.yaml#/ValidationErrorResponse"
    FieldError:
      $ref: "common/schemas/errors.yaml#/FieldError"
    PageableInfo:
      $ref: "common/schemas/pagination.yaml#/PageableInfo"

  securitySchemes:
    CookieAuth:
      $ref: "common/security.yaml#/securitySchemes/CookieAuth"

security:
  - CookieAuth: []
