openapi: 3.1.1
info:
  title: Pricing API
  description: Pricing calculation API for dry cleaning services
  version: 1.0.0
  contact:
    name: API Support
    email: support@dryclean.example.com

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.dryclean.example.com
    description: Production

tags:
  - name: pricing
    description: Pricing calculations

paths:
  /api/pricing/calculate:
    post:
      operationId: calculatePrice
      summary: Calculate price for items
      description: Calculate price for one or more items with modifiers
      tags:
        - pricing
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriceCalculationRequest'
      responses:
        '200':
          description: Price calculation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceCalculationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/pricing/modifiers:
    get:
      operationId: listPriceModifiers
      summary: List available price modifiers
      description: Get list of all available price modifiers
      tags:
        - pricing
      security:
        - cookieAuth: []
      parameters:
        - name: categoryCode
          in: query
          description: Filter by category code
          required: false
          schema:
            type: string
        - name: active
          in: query
          description: Filter by active status
          required: false
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: List of price modifiers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceModifiersResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/pricing/discounts:
    get:
      operationId: listDiscounts
      summary: List available discounts
      description: Get list of all available discount types
      tags:
        - pricing
      security:
        - cookieAuth: []
      parameters:
        - name: active
          in: query
          description: Filter by active status
          required: false
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: List of discounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscountsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    PriceCalculationRequest:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/PriceCalculationItem'
          description: Items to calculate price for
        globalModifiers:
          $ref: '#/components/schemas/GlobalPriceModifiers'
          description: Global modifiers (urgency, discount)

    PriceCalculationItem:
      type: object
      required:
        - priceListItemId
        - quantity
      properties:
        priceListItemId:
          type: string
          format: uuid
          description: Price list item ID
        quantity:
          type: integer
          minimum: 1
          description: Quantity (in units)
        characteristics:
          $ref: '#/components/schemas/ItemCharacteristics'
          description: Item characteristics
        modifierCodes:
          type: array
          items:
            type: string
          description: Modifier codes to apply

    ItemCharacteristics:
      type: object
      properties:
        material:
          type: string
          description: Material type
        color:
          type: string
          description: Item color (affects dyeing price)
        wearLevel:
          type: integer
          enum: [10, 30, 50, 75]
          description: Wear level percentage

    GlobalPriceModifiers:
      type: object
      properties:
        urgencyType:
          type: string
          enum: [NORMAL, EXPRESS_48H, EXPRESS_24H]
          default: NORMAL
          description: |
            Urgency type:
            * `NORMAL` - Standard processing
            * `EXPRESS_48H` - Express 48 hours (+50%)
            * `EXPRESS_24H` - Express 24 hours (+100%)
        discountType:
          type: string
          enum: [NONE, EVERCARD, SOCIAL_MEDIA, MILITARY, OTHER]
          default: NONE
          description: |
            Discount type:
            * `NONE` - No discount
            * `EVERCARD` - Evercard discount (10%)
            * `SOCIAL_MEDIA` - Social media discount (5%)
            * `MILITARY` - Military discount (10%)
            * `OTHER` - Other discount
        discountPercentage:
          type: integer
          minimum: 0
          maximum: 100
          description: Discount percentage (required for OTHER type)

    PriceCalculationResponse:
      type: object
      required:
        - items
        - totals
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CalculatedItemPrice'
          description: Calculated prices for each item
        totals:
          $ref: '#/components/schemas/CalculationTotals'
          description: Total calculation summary
        warnings:
          type: array
          items:
            type: string
          description: Calculation warnings (e.g., discount not applicable)

    CalculatedItemPrice:
      type: object
      required:
        - priceListItemId
        - itemName
        - quantity
        - basePrice
        - calculations
        - total
      properties:
        priceListItemId:
          type: string
          format: uuid
        itemName:
          type: string
          description: Item name from price list
        categoryCode:
          type: string
          description: Category code
        quantity:
          type: integer
        basePrice:
          type: integer
          description: Base price per unit in kopiykas
        calculations:
          $ref: '#/components/schemas/ItemPriceCalculation'
          description: Detailed price calculation
        total:
          type: integer
          description: Total price for this item in kopiykas

    ItemPriceCalculation:
      type: object
      required:
        - baseAmount
        - modifiers
        - subtotal
        - urgencyModifier
        - discountModifier
        - finalAmount
      properties:
        baseAmount:
          type: integer
          description: Base amount (base price × quantity) in kopiykas
        modifiers:
          type: array
          items:
            $ref: '#/components/schemas/AppliedModifier'
          description: Applied modifiers with amounts
        modifiersTotal:
          type: integer
          description: Total modifiers amount in kopiykas
        subtotal:
          type: integer
          description: Subtotal (base + modifiers) in kopiykas
        urgencyModifier:
          $ref: '#/components/schemas/AppliedModifier'
          description: Applied urgency modifier
        discountModifier:
          $ref: '#/components/schemas/AppliedModifier'
          description: Applied discount modifier
        discountEligible:
          type: boolean
          description: Whether item is eligible for discount
        finalAmount:
          type: integer
          description: Final amount after all calculations in kopiykas

    AppliedModifier:
      type: object
      required:
        - code
        - name
        - type
        - value
        - amount
      properties:
        code:
          type: string
          description: Modifier code
        name:
          type: string
          description: Modifier name
        type:
          type: string
          enum: [PERCENTAGE, FIXED]
          description: Modifier type
        value:
          type: number
          description: Modifier value (percentage or fixed amount)
        amount:
          type: integer
          description: Calculated amount in kopiykas

    CalculationTotals:
      type: object
      required:
        - itemsSubtotal
        - urgencyAmount
        - discountAmount
        - discountApplicableAmount
        - total
      properties:
        itemsSubtotal:
          type: integer
          description: Sum of all items subtotals in kopiykas
        urgencyAmount:
          type: integer
          description: Total urgency surcharge in kopiykas
        urgencyPercentage:
          type: integer
          description: Applied urgency percentage
        discountAmount:
          type: integer
          description: Total discount amount in kopiykas
        discountPercentage:
          type: integer
          description: Applied discount percentage
        discountApplicableAmount:
          type: integer
          description: Amount eligible for discount in kopiykas
        total:
          type: integer
          description: Final total amount in kopiykas

    PriceModifier:
      type: object
      required:
        - code
        - name
        - type
        - value
        - active
      properties:
        code:
          type: string
          description: Unique modifier code
        name:
          type: string
          description: Modifier name
        description:
          type: string
          description: Modifier description
        type:
          type: string
          enum: [PERCENTAGE, FIXED]
          description: Modifier type
        value:
          type: number
          description: Modifier value
        categoryRestrictions:
          type: array
          items:
            type: string
          description: Category codes where modifier is applicable
        active:
          type: boolean
          description: Is modifier active

    Discount:
      type: object
      required:
        - code
        - name
        - percentage
        - active
      properties:
        code:
          type: string
          description: Discount code
        name:
          type: string
          description: Discount name
        description:
          type: string
          description: Discount description
        percentage:
          type: integer
          minimum: 0
          maximum: 100
          description: Discount percentage
        excludedCategories:
          type: array
          items:
            type: string
          description: Category codes excluded from discount
        active:
          type: boolean
          description: Is discount active

    PriceModifiersResponse:
      type: object
      required:
        - modifiers
      properties:
        modifiers:
          type: array
          items:
            $ref: '#/components/schemas/PriceModifier'
          description: List of price modifiers
        generalModifiers:
          type: array
          items:
            $ref: '#/components/schemas/PriceModifier'
          description: General modifiers (applicable to all categories)
        textileModifiers:
          type: array
          items:
            $ref: '#/components/schemas/PriceModifier'
          description: Textile-specific modifiers
        leatherModifiers:
          type: array
          items:
            $ref: '#/components/schemas/PriceModifier'
          description: Leather-specific modifiers

    DiscountsResponse:
      type: object
      required:
        - discounts
      properties:
        discounts:
          type: array
          items:
            $ref: '#/components/schemas/Discount'
          description: List of available discounts

    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
        details:
          type: object
          additionalProperties: true
          description: Additional error details

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSION
      description: Session-based authentication using httpOnly cookies