openapi: 3.1.1
info:
  title: Price List API
  description: Price list management API
  version: 1.0.0
  contact:
    name: API Support
    email: support@dryclean.example.com

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.dryclean.example.com
    description: Production

tags:
  - name: price-list
    description: Price list operations

paths:
  /api/price-list:
    get:
      operationId: listPriceListItems
      summary: List price list items
      description: Get list of price list items
      tags:
        - price-list
      security:
        - cookieAuth: []
      parameters:
        - name: categoryCode
          in: query
          description: Filter by category code
          required: false
          schema:
            $ref: '#/components/schemas/ServiceCategoryType'
        - name: active
          in: query
          description: Filter by active status
          required: false
          schema:
            type: boolean
            default: true
        - name: offset
          in: query
          description: Number of items to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: limit
          in: query
          description: Number of items to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: List of price list items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceListItemsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
    
    post:
      operationId: createPriceListItem
      summary: Create new price list item
      description: Create a new price list item (admin only)
      tags:
        - price-list
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePriceListItemRequest'
      responses:
        '201':
          description: Price list item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceListItemInfo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/price-list/{priceListItemId}:
    parameters:
      - name: priceListItemId
        in: path
        required: true
        description: Price list item ID
        schema:
          type: string
          format: uuid
    
    get:
      operationId: getPriceListItemById
      summary: Get price list item details
      description: Get detailed price list item information
      tags:
        - price-list
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Price list item details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceListItemInfo'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    
    put:
      operationId: updatePriceListItem
      summary: Update price list item
      description: Update an existing price list item (admin only)
      tags:
        - price-list
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePriceListItemRequest'
      responses:
        '200':
          description: Price list item updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceListItemInfo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    
    delete:
      operationId: deletePriceListItem
      summary: Delete price list item
      description: Delete a price list item (admin only)
      tags:
        - price-list
      security:
        - cookieAuth: []
      responses:
        '204':
          description: Price list item deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    Forbidden:
      description: Forbidden access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    Conflict:
      description: Resource conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    ServiceCategoryType:
      type: string
      enum:
        - CLOTHING
        - LAUNDRY
        - IRONING
        - LEATHER
        - PADDING
        - FUR
        - DYEING
        - ADDITIONAL_SERVICES
      description: |
        Service category types from price list:
        * `CLOTHING` - Clothing and textile items
        * `LAUNDRY` - Washing services
        * `IRONING` - Ironing services
        * `LEATHER` - Leather items
        * `PADDING` - Padded items
        * `FUR` - Fur items
        * `DYEING` - Dyeing services
        * `ADDITIONAL_SERVICES` - Additional services

    UnitOfMeasure:
      type: string
      enum:
        - PIECE
        - KILOGRAM
        - PAIR
        - SQUARE_METER
      description: |
        Unit of measure:
        * `PIECE` - Piece (шт)
        * `KILOGRAM` - Kilogram (кг)
        * `PAIR` - Pair (пара)
        * `SQUARE_METER` - Square meter (кв.м)

    PriceListItemInfo:
      type: object
      required:
        - id
        - categoryCode
        - catalogNumber
        - name
        - unitOfMeasure
        - basePrice
        - active
      properties:
        id:
          type: string
          format: uuid
          description: Price list item ID
        categoryCode:
          $ref: '#/components/schemas/ServiceCategoryType'
          description: Service category code
        catalogNumber:
          type: integer
          description: Catalog number
        name:
          type: string
          description: Item name
        unitOfMeasure:
          $ref: '#/components/schemas/UnitOfMeasure'
          description: Unit of measure
        basePrice:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Base price in kopiykas (1 kopiykas = 0.01 UAH)
        priceBlack:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Price for black dyeing in kopiykas (1 kopiykas = 0.01 UAH)
        priceColor:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Price for color dyeing in kopiykas (1 kopiykas = 0.01 UAH)
        active:
          type: boolean
          description: Is item active
        processingTimeDays:
          type: integer
          description: Processing time in days
          default: 3
        expressAvailable:
          type: boolean
          description: Is express service available
          default: false
        expressTimeHours:
          type: integer
          description: Express processing time in hours
        expressPrice:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Express service price in kopiykas
        sortOrder:
          type: integer
          description: Sort order for display
          default: "0"
        description:
          type: string
          description: Service/item description
        nameUa:
          type: string
          description: Ukrainian name

    CreatePriceListItemRequest:
      type: object
      required:
        - categoryCode
        - catalogNumber
        - name
        - unitOfMeasure
        - basePrice
      properties:
        categoryCode:
          $ref: '#/components/schemas/ServiceCategoryType'
          description: Service category code
        catalogNumber:
          type: integer
          description: Catalog number
        name:
          type: string
          description: Item name
        unitOfMeasure:
          $ref: '#/components/schemas/UnitOfMeasure'
          description: Unit of measure
        basePrice:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Base price in kopiykas
        priceBlack:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Price for black dyeing
        priceColor:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Price for color dyeing
        active:
          type: boolean
          description: Is item active
          default: true
        processingTimeDays:
          type: integer
          description: Processing time in days
          default: 3
        expressAvailable:
          type: boolean
          description: Is express service available
          default: false
        expressTimeHours:
          type: integer
          description: Express processing time in hours
        expressPrice:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Express service price
        sortOrder:
          type: integer
          description: Sort order for display
          default: "0"
        description:
          type: string
          description: Service/item description
        nameUa:
          type: string
          description: Ukrainian name

    UpdatePriceListItemRequest:
      type: object
      properties:
        name:
          type: string
          description: Item name
        basePrice:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Base price in kopiykas
        priceBlack:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Price for black dyeing
        priceColor:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Price for color dyeing
        active:
          type: boolean
          description: Is item active
        processingTimeDays:
          type: integer
          description: Processing time in days
        expressAvailable:
          type: boolean
          description: Is express service available
        expressTimeHours:
          type: integer
          description: Express processing time in hours
        expressPrice:
          type: integer
          minimum: 0
          maximum: 999999999
          description: Express service price
        sortOrder:
          type: integer
          description: Sort order for display
          default: "0"
        description:
          type: string
          description: Service/item description
        nameUa:
          type: string
          description: Ukrainian name

    PriceListItemsResponse:
      type: object
      required:
        - priceListItems
        - totalItems
        - hasMore
      properties:
        priceListItems:
          type: array
          items:
            $ref: '#/components/schemas/PriceListItemInfo'
          description: List of price list items
        totalItems:
          type: integer
          description: Total number of items matching the filter
        hasMore:
          type: boolean
          description: Whether there are more items to load

    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
        details:
          type: object
          additionalProperties: true
          description: Additional error details

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSION
      description: Session-based authentication using httpOnly cookies