openapi: 3.0.4
info:
  title: User Domain API
  description: API для управління користувачами (операторами) системи хімчистки
  version: 1.0.0
  contact:
    name: AKSI Development Team
    email: dev@aksi.com
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.aksi.com
    description: Production server
tags:
  - name: users
    description: Управління користувачами системи

paths:
  # User Management
  /api/users/me:
    $ref: "user/paths/user-management.yaml#/~1api~1users~1me"
  /api/users:
    $ref: "user/paths/user-management.yaml#/~1api~1users"
  /api/users/{id}:
    $ref: "user/paths/user-management.yaml#/~1api~1users~1{id}"
  /api/users/{id}/role:
    $ref: "user/paths/user-management.yaml#/~1api~1users~1{id}~1role"
  /api/users/{id}/status:
    $ref: "user/paths/user-management.yaml#/~1api~1users~1{id}~1status"
  /api/users/{id}/password:
    $ref: "user/paths/user-management.yaml#/~1api~1users~1{id}~1password"

components:
  schemas:
    # Request Schemas
    CreateUserRequest:
      $ref: "user/schemas/user-requests.yaml#/CreateUserRequest"
    UpdateUserRequest:
      $ref: "user/schemas/user-requests.yaml#/UpdateUserRequest"
    UpdateUserRoleRequest:
      $ref: "user/schemas/user-requests.yaml#/UpdateUserRoleRequest"
    UpdateUserStatusRequest:
      $ref: "user/schemas/user-requests.yaml#/UpdateUserStatusRequest"
    ChangePasswordRequest:
      $ref: "user/schemas/user-requests.yaml#/ChangePasswordRequest"
    
    # Response Schemas
    UserResponse:
      $ref: "user/schemas/user-responses.yaml#/UserResponse"
    UserListResponse:
      $ref: "user/schemas/user-responses.yaml#/UserListResponse"
    
    # Enums
    UserRole:
      $ref: "user/schemas/user-enums.yaml#/UserRole"

    # Common Schemas (використовуємо спільні)
    ErrorResponse:
      $ref: "common/schemas/errors.yaml#/ErrorResponse"
    ValidationErrorResponse:
      $ref: "common/schemas/errors.yaml#/ValidationErrorResponse"
    FieldError:
      $ref: "common/schemas/errors.yaml#/FieldError"

  securitySchemes:
    CookieAuth:
      $ref: "common/security.yaml#/securitySchemes/CookieAuth"

# Всі endpoints потребують автентифікації
security:
  - CookieAuth: []