/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { ClientSearchRequestSourceType } from './clientSearchRequestSourceType';
import type { ClientSearchRequestCommunicationMethodsItem } from './clientSearchRequestCommunicationMethodsItem';
import type { ClientSearchRequestSort } from './clientSearchRequestSort';

export interface ClientSearchRequest {
  /**
   * Загальний пошуковий запит
   * @minLength 2
   * @maxLength 100
   */
  query?: string;
  /**
   * Фільтр за ім'ям
   * @minLength 0
   * @maxLength 50
   */
  firstName?: string;
  /**
   * Фільтр за прізвищем
   * @minLength 0
   * @maxLength 50
   */
  lastName?: string;
  /** Фільтр за телефоном */
  phone?: string;
  /** Фільтр за email */
  email?: string;
  /**
   * Фільтр за містом
   * @minLength 0
   * @maxLength 100
   */
  city?: string;
  sourceType?: ClientSearchRequestSourceType;
  communicationMethods?: ClientSearchRequestCommunicationMethodsItem[];
  /** Дата в ISO 8601 форматі */
  registrationDateFrom?: string;
  /** Дата в ISO 8601 форматі */
  registrationDateTo?: string;
  /** Фільтр VIP клієнтів */
  isVip?: boolean;
  /**
   * Номер сторінки
   * @minimum 0
   */
  page?: number;
  /**
   * Розмір сторінки
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Поле для сортування */
  sort?: ClientSearchRequestSort;
}
