/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

/**
 * Поле для сортування
 */
export type ClientSearchRequestSort = typeof ClientSearchRequestSort[keyof typeof ClientSearchRequestSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientSearchRequestSort = {
  firstName: 'firstName',
  lastName: 'lastName',
  phone: 'phone',
  createdAt: 'createdAt',
  totalOrders: 'totalOrders',
  totalSpent: 'totalSpent',
} as const;
