---
openapi: 3.0.4
info:
  title: Customer API
  description: Customer management API for dry cleaning service
  version: 1.0.0
  contact:
    name: API Support
    email: support@dryclean.example.com

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.dryclean.example.com
    description: Production

tags:
  - name: customer
    description: Customer management operations

paths:
  /api/customers:
    $ref: "./paths/customer-paths.yaml#/paths/~1api~1customers"
  /api/customers/{customerId}:
    $ref: "./paths/customer-paths.yaml#/paths/~1api~1customers~1[customerId]"
  /api/customers/{customerId}/exists:
    $ref: "./paths/customer-paths.yaml#/paths/~1api~1customers~1[customerId]~1exists"

components:
  responses:
    BadRequest:
      $ref: "../common.yaml#/components/responses/BadRequest"
    Unauthorized:
      $ref: "../common.yaml#/components/responses/Unauthorized"
    Forbidden:
      $ref: "../common.yaml#/components/responses/Forbidden"
    NotFound:
      $ref: "../common.yaml#/components/responses/NotFound"
    Conflict:
      $ref: "../common.yaml#/components/responses/Conflict"

  parameters:
    Search:
      $ref: "../common.yaml#/components/parameters/Search"

  schemas:
    CustomerInfo:
      $ref: "./schemas/customer-schemas.yaml#/components/schemas/CustomerInfo"
    CreateCustomerRequest:
      $ref: "./schemas/customer-schemas.yaml#/components/schemas/CreateCustomerRequest"
    UpdateCustomerRequest:
      $ref: "./schemas/customer-schemas.yaml#/components/schemas/UpdateCustomerRequest"
    CustomerListResponse:
      $ref: "./schemas/customer-schemas.yaml#/components/schemas/CustomerListResponse"
    PhoneNumber:
      $ref: "../common.yaml#/components/schemas/PhoneNumber"
    Email:
      $ref: "../common.yaml#/components/schemas/Email"
    ContactPreference:
      $ref: "../common.yaml#/components/schemas/ContactPreference"
    InfoSource:
      $ref: "../common.yaml#/components/schemas/InfoSource"
    PaginatedResponse:
      $ref: "../common.yaml#/components/schemas/PaginatedResponse"

security:
  - cookieAuth: []
  - bearerAuth: []
