---
openapi: 3.0.4
info:
  title: Price List API
  description: Price list management API for dry cleaning service
  version: 1.0.0
  contact:
    name: API Support
    email: support@dryclean.example.com

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.dryclean.example.com
    description: Production

tags:
  - name: price-list
    description: Price list management operations

paths:
  /api/price-list:
    $ref: "./paths/price-list-paths.yaml#/paths/~1api~1price-list"
  /api/price-list/{priceListItemId}:
    $ref: "./paths/price-list-paths.yaml#/paths/~1api~1price-list~1{priceListItemId}"

components:
  responses:
    BadRequest:
      $ref: "../common.yaml#/components/responses/BadRequest"
    Unauthorized:
      $ref: "../common.yaml#/components/responses/Unauthorized"
    Forbidden:
      $ref: "../common.yaml#/components/responses/Forbidden"
    NotFound:
      $ref: "../common.yaml#/components/responses/NotFound"

  parameters:
    PageNumber:
      $ref: "../common.yaml#/components/parameters/PageNumber"
    PageSize:
      $ref: "../common.yaml#/components/parameters/PageSize"
    SortBy:
      $ref: "../common.yaml#/components/parameters/SortBy"
    SortOrder:
      $ref: "../common.yaml#/components/parameters/SortOrder"

  schemas:
    PriceListItemInfo:
      $ref: "./schemas/price-list-schemas.yaml#/components/schemas/PriceListItemInfo"
    CreatePriceListItemRequest:
      $ref: "./schemas/price-list-schemas.yaml#/components/schemas/CreatePriceListItemRequest"
    UpdatePriceListItemRequest:
      $ref: "./schemas/price-list-schemas.yaml#/components/schemas/UpdatePriceListItemRequest"
    PriceListItemsResponse:
      $ref: "./schemas/price-list-schemas.yaml#/components/schemas/PriceListItemsResponse"
    ServiceCategoryType:
      $ref: "../common.yaml#/components/schemas/ServiceCategoryType"
    UnitOfMeasure:
      $ref: "../common.yaml#/components/schemas/UnitOfMeasure"

security:
  - cookieAuth: []
  - bearerAuth: []
