# Базові спільні схеми для всіх доменів
UUID:
  type: string
  format: uuid
  description: Унікальний ідентифікатор (UUID v4)
  example: 550e8400-e29b-41d4-a716-446655440000
  nullable: false

Timestamp:
  type: string
  format: date-time
  description: Мітка часу в ISO 8601 форматі
  example: 2025-01-07T10:30:00Z
  nullable: false

Date:
  type: string
  format: date
  description: Дата в ISO 8601 форматі
  example: 2025-01-07
  nullable: false

TimestampProperties:
  type: object
  title: TimestampProperties
  properties:
    createdAt:
      type: string
      format: date-time
      description: Дата створення
      readOnly: true
      nullable: false
    updatedAt:
      type: string
      format: date-time
      description: Дата останнього оновлення
      readOnly: true

BaseEntityResponse:
  type: object
  title: BaseEntityResponse
  required:
    - id
    - createdAt
  properties:
    id:
      $ref: "#/UUID"
      nullable: false
    createdAt:
      $ref: "#/Timestamp"
      nullable: false
    updatedAt:
      $ref: "#/Timestamp"

Money:
  type: number
  format: double
  minimum: 0
  multipleOf: 0.01
  description: Грошова сума (в гривнях)
  example: 150.50
  nullable: false

Percentage:
  type: number
  format: double
  minimum: 0
  maximum: 100
  description: Відсоток (0-100)
  example: 15.5
  nullable: false

Email:
  type: string
  format: email
  nullable: false
  minLength: 3
  maxLength: 100
  pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
  description: Email адреса
  example: user@example.com

PhoneNumber:
  type: string
  pattern: '^\+380[\s\-]?(\(?\d{2}\)?[\s\-]?\d{3}[\s\-]?\d{2}[\s\-]?\d{2}|\d{9})$'
  description: Номер телефону в міжнародному форматі (+380501234567, +380 50 123 45 67, +380 (50) 123-45-67)
  example: "+380501234567"
  nullable: false

PositiveInteger:
  type: integer
  minimum: 1
  description: Позитивне ціле число
  example: 5
  nullable: false

FileSize:
  type: integer
  format: int64
  minimum: 0
  description: Розмір файлу в байтах
  example: 1048576
  nullable: false

Url:
  type: string
  format: uri
  pattern: '^https?://[\w\-]+(\.[\w\-]+)+[/#?]?.*$'
  description: URL адреса
  example: https://example.com/resource
  nullable: false
