openapi: 3.0.4
info:
  title: Calculator API
  description: Price calculation operations
  version: 1.0.0

paths:
  /game-services/calculate:
    post:
      tags: [calculator]
      operationId: calculatePrice
      summary: Calculate service price
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalculationRequest"
      responses:
        "200":
          description: Calculation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CalculationResult"

components:
  schemas:
    CalculationRequest:
      type: object
      properties:
        gameCode:
          type: string
          description: Game code
          example: "WOW"
        serviceTypeCode:
          type: string
          description: Service type code
          example: "LEVEL_BOOST"
        difficultyLevelCode:
          type: string
          description: Difficulty level code
          example: "01-60"
        targetLevel:
          type: integer
          description: Target level
          example: 60
        startLevel:
          type: integer
          description: Starting level
          default: 1
          example: 1
        modifiers:
          type: array
          items:
            type: string
          description: List of modifier codes to apply
          example: ["RUSH", "PREMIUM"]
      required:
        - gameCode
        - serviceTypeCode
        - difficultyLevelCode

    CalculationResult:
      type: object
      properties:
        finalPrice:
          type: integer
          description: Final price in cents
          example: 15000
        currency:
          type: string
          default: "USD"
          example: "USD"
        breakdown:
          $ref: "#/components/schemas/CalculationBreakdown"
      required:
        - finalPrice
        - breakdown

    CalculationBreakdown:
      type: object
      properties:
        basePrice:
          type: integer
          description: Base price in cents
          example: 10000
        difficultyMultiplier:
          type: integer
          minimum: 1
          maximum: 1000
          description: Difficulty multiplier in basis points (100 = 1.0x)
          example: 100
        serviceMultiplier:
          type: integer
          minimum: 1
          maximum: 1000
          description: Service multiplier in basis points (100 = 1.0x)
          example: 100
        levelAdjustment:
          type: integer
          description: Level-based adjustment in cents
          example: 2500
        totalAdjustment:
          type: integer
          description: Total adjustment in cents
          example: 2500
      required:
        - basePrice
        - difficultyMultiplier
        - serviceMultiplier
        - totalAdjustment
