openapi: 3.0.4
info:
  title: Difficulty Levels API
  description: Difficulty level management operations
  version: 1.0.0

paths:
  /game-services/difficulty-levels:
    get:
      tags: [difficulty-levels]
      operationId: listDifficultyLevels
      summary: Get difficulty levels
      parameters:
        - $ref: "../common.yaml#/components/parameters/PageNumber"
        - $ref: "../common.yaml#/components/parameters/PageSize"
        - name: gameId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by game ID
        - name: active
          in: query
          schema:
            type: boolean
          description: Filter by active status
      responses:
        "200":
          description: List of difficulty levels
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DifficultyLevelListResponse"

    post:
      tags: [difficulty-levels]
      operationId: createDifficultyLevel
      summary: Create difficulty level
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDifficultyLevelRequest"
      responses:
        "201":
          description: Difficulty level created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DifficultyLevel"

  /game-services/difficulty-levels/{id}:
    get:
      tags: [difficulty-levels]
      operationId: getDifficultyLevelById
      summary: Get difficulty level by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Difficulty level found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DifficultyLevel"

    put:
      tags: [difficulty-levels]
      operationId: updateDifficultyLevel
      summary: Update difficulty level
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDifficultyLevelRequest"
      responses:
        "200":
          description: Difficulty level updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DifficultyLevel"

    delete:
      tags: [difficulty-levels]
      operationId: deleteDifficultyLevel
      summary: Delete difficulty level
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Difficulty level deleted

components:
  schemas:
    DifficultyLevel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        gameId:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 100
        code:
          type: string
          minLength: 1
          maxLength: 50
          pattern: "^[A-Z0-9_-]+$"
        levelValue:
          type: integer
          minimum: 1
          maximum: 1000
        description:
          type: string
          maxLength: 500
        active:
          type: boolean
          default: true
        sortOrder:
          type: integer
          minimum: 0
          default: 0
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - gameId
        - name
        - code
        - levelValue
        - active
        - sortOrder

    CreateDifficultyLevelRequest:
      type: object
      properties:
        gameId:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 100
        code:
          type: string
          minLength: 1
          maxLength: 50
          pattern: "^[A-Z0-9_-]+$"
        levelValue:
          type: integer
          minimum: 1
          maximum: 1000
        description:
          type: string
          maxLength: 500
        sortOrder:
          type: integer
          minimum: 0
          default: 0
      required:
        - gameId
        - name
        - code
        - levelValue

    UpdateDifficultyLevelRequest:
      type: object
      properties:
        gameId:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 100
        code:
          type: string
          minLength: 1
          maxLength: 50
          pattern: "^[A-Z0-9_-]+$"
        levelValue:
          type: integer
          minimum: 1
          maximum: 1000
        description:
          type: string
          maxLength: 500
        sortOrder:
          type: integer
          minimum: 0
        active:
          type: boolean
      required: []

    DifficultyLevelListResponse:
      type: object
      required:
        - data
        - totalElements
        - totalPages
        - size
        - number
        - numberOfElements
        - first
        - last
        - empty
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/DifficultyLevel"
          description: Page content
        totalElements:
          type: integer
          format: int64
          description: Total number of elements
        totalPages:
          type: integer
          description: Total number of pages
        size:
          type: integer
          description: Page size
        number:
          type: integer
          description: Page number (0-based)
        numberOfElements:
          type: integer
          description: Number of elements in current page
        first:
          type: boolean
          description: Is first page
        last:
          type: boolean
          description: Is last page
        empty:
          type: boolean
          description: Is empty
