openapi: 3.0.4
info:
  title: Price Configurations API
  description: Price configuration management operations
  version: 1.0.0

paths:
  /game-services/price-configurations:
    get:
      tags: [price-configurations]
      operationId: listPriceConfigurations
      summary: Get price configurations
      parameters:
        - $ref: "../common.yaml#/components/parameters/PageNumber"
        - $ref: "../common.yaml#/components/parameters/PageSize"
        - name: gameId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by game ID
        - name: serviceTypeId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by service type ID
        - name: difficultyLevelId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by difficulty level ID
        - name: active
          in: query
          schema:
            type: boolean
          description: Filter by active status
      responses:
        "200":
          description: List of price configurations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceConfigurationListResponse"

    post:
      tags: [price-configurations]
      operationId: createPriceConfiguration
      summary: Create price configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePriceConfigurationRequest"
      responses:
        "201":
          description: Price configuration created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceConfiguration"

  /game-services/price-configurations/{id}:
    get:
      tags: [price-configurations]
      operationId: getPriceConfigurationById
      summary: Get price configuration by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Price configuration found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceConfiguration"

    put:
      tags: [price-configurations]
      operationId: updatePriceConfiguration
      summary: Update price configuration
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePriceConfigurationRequest"
      responses:
        "200":
          description: Price configuration updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceConfiguration"

    delete:
      tags: [price-configurations]
      operationId: deletePriceConfiguration
      summary: Delete price configuration
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Price configuration deleted

components:
  schemas:
    PriceConfiguration:
      type: object
      properties:
        id:
          type: string
          format: uuid
        gameId:
          type: string
          format: uuid
        difficultyLevelId:
          type: string
          format: uuid
        serviceTypeId:
          type: string
          format: uuid
        basePrice:
          type: integer
          minimum: 0
          description: Base price in cents (e.g., 100 = $1.00)
        pricePerLevel:
          type: integer
          minimum: 0
          default: 0
          description: Price per level in cents
        currency:
          type: string
          default: "USD"
        calculationType:
          type: string
          enum: [LINEAR, RANGE, FORMULA, TIME_BASED]
        calculationFormula:
          type: string
          description: JSON formula configuration
        active:
          type: boolean
          default: true
        sortOrder:
          type: integer
          minimum: 0
          default: 0
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - gameId
        - difficultyLevelId
        - serviceTypeId
        - basePrice
        - calculationType
        - active
        - sortOrder

    CreatePriceConfigurationRequest:
      type: object
      properties:
        gameId:
          type: string
          format: uuid
        difficultyLevelId:
          type: string
          format: uuid
        serviceTypeId:
          type: string
          format: uuid
        basePrice:
          type: integer
          minimum: 0
          description: Base price in cents
        pricePerLevel:
          type: integer
          minimum: 0
          default: 0
          description: Price per level in cents
        currency:
          type: string
          default: "USD"
        calculationType:
          type: string
          enum: [LINEAR, RANGE, FORMULA, TIME_BASED]
        calculationFormula:
          type: string
          description: JSON formula configuration
        sortOrder:
          type: integer
          minimum: 0
          default: 0
        active:
          type: boolean
          default: true
      required:
        - gameId
        - difficultyLevelId
        - serviceTypeId
        - basePrice
        - calculationType

    UpdatePriceConfigurationRequest:
      type: object
      properties:
        gameId:
          type: string
          format: uuid
        difficultyLevelId:
          type: string
          format: uuid
        serviceTypeId:
          type: string
          format: uuid
        basePrice:
          type: integer
          minimum: 0
          description: Base price in cents
        pricePerLevel:
          type: integer
          minimum: 0
          description: Price per level in cents
        currency:
          type: string
        calculationType:
          type: string
          enum: [LINEAR, RANGE, FORMULA, TIME_BASED]
        calculationFormula:
          type: string
        sortOrder:
          type: integer
          minimum: 0
        active:
          type: boolean
      required: []

    PriceConfigurationListResponse:
      type: object
      required:
        - data
        - totalElements
        - totalPages
        - size
        - number
        - numberOfElements
        - first
        - last
        - empty
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/PriceConfiguration"
          description: Page content
        totalElements:
          type: integer
          format: int64
          description: Total number of elements
        totalPages:
          type: integer
          description: Total number of pages
        size:
          type: integer
          description: Page size
        number:
          type: integer
          description: Page number (0-based)
        numberOfElements:
          type: integer
          description: Number of elements in current page
        first:
          type: boolean
          description: Is first page
        last:
          type: boolean
          description: Is last page
        empty:
          type: boolean
          description: Is empty
