# Docker Compose конфігурація для розробки з бекендом на хост системі
# Використання: docker-compose -f docker-compose.host-backend.yml up
#
# Запустити бекенд локально з такими параметрами:
# SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/aksi_cleaners_db_v5
# SPRING_DATASOURCE_USERNAME=aksi_user
# SPRING_DATASOURCE_PASSWORD=1911
# SPRING_PROFILES_ACTIVE=dev
#
# Або через IntelliJ IDEA / VS Code з конфігурацією для Spring Boot

services:
  # Traefik - зворотний проксі для маршрутизації
  traefik:
    image: traefik:v3.4
    container_name: traefik-host-backend
    ports:
      - "80:80" # HTTP порт
      - "9090:8080" # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      # Налаштування Docker провайдера
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Налаштування точок входу
      - "--entrypoints.web.address=:80"
      # Включення API Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # Налаштування логування
      - "--log.level=INFO"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - aksi-network-host
    restart: unless-stopped

  # PostgreSQL - база даних
  postgres:
    image: postgres:17
    container_name: postgres-host-backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aksi_user
      POSTGRES_PASSWORD: 1911
      POSTGRES_DB: aksi_cleaners_db_v5
      POSTGRES_SCHEMA: public
    volumes:
      - postgres_data_host:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aksi_user -d aksi_cleaners_db_v5"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aksi-network-host

  # PgAdmin - адміністрування бази даних
  pgadmin:
    image: dpage/pgadmin4:9.5
    container_name: aksi-pgadmin-host-backend
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aksi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pgadmin_data_host:/var/lib/pgadmin
      - ./pgadmin/config/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aksi-network-host

  # Frontend (Next.js) - розробка
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-host-backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      # API URL для клієнтської частини (browser) - через хост систему
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
      # API URL для серверної частини (SSR) - прямо до хост системи
      NEXT_SERVER_API_URL: http://host.docker.internal:8080/api
      NEXT_TELEMETRY_DISABLED: 1
      # Orval конфігурація для генерації API
      ORVAL_API_URL: http://host.docker.internal:8080/api/v3/api-docs
      # 🚀 NPM ОПТИМІЗАЦІЯ для прискорення
      npm_config_audit: "false"
      npm_config_fund: "false"
      npm_config_progress: "false"
      npm_config_cache_max: "86400000"
      npm_config_maxsockets: "20"
      npm_config_audit_level: "none"
    volumes:
      - ../frontend:/app # Монтуємо весь проект для автоматичного перезавантаження
      - frontend_node_modules_host:/app/node_modules # Зберігаємо node_modules у volume
      - frontend_next_cache_host:/app/.next # Зберігаємо .next кеш у volume
      - frontend_npm_cache_host:/home/node/.npm # Зберігаємо npm кеш у volume
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      traefik:
        condition: service_started
    restart: unless-stopped
    networks:
      - aksi-network-host
    # Додаємо healthcheck для Next.js
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s # Даємо час на запуск Next.js
    labels:
      # Налаштування Traefik
      - "traefik.enable=true"
      # Правило маршрутизації - всі запити, які не починаються з /api
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      # Пріоритет - низький, щоб дозволити спочатку обробити /api запити
      - "traefik.http.routers.frontend.priority=1"
      # Вказуємо на якому порті працює сервіс
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  # Portainer - управління Docker контейнерами (опціонально)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-host-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_host:/data
    networks:
      - aksi-network-host
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  aksi-network-host:
    driver: bridge

volumes:
  postgres_data_host:
  pgadmin_data_host:
  frontend_node_modules_host:
  frontend_next_cache_host:
  frontend_npm_cache_host:
  portainer_data_host:
