/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from './address';
import type { ClientResponseCommunicationMethodsItem } from './clientResponseCommunicationMethodsItem';
import type { ClientResponseSourceType } from './clientResponseSourceType';
import type { ClientStatistics } from './clientStatistics';

export interface ClientResponse {
  /** Унікальний ідентифікатор (UUID v4) */
  id: string;
  /** Ім'я клієнта */
  firstName: string;
  /** Прізвище клієнта */
  lastName: string;
  /** Повне ім'я (firstName + lastName) */
  readonly fullName?: string;
  /** Номер телефону */
  phone: string;
  /** Email адреса */
  email?: string;
  address?: Address;
  communicationMethods?: ClientResponseCommunicationMethodsItem[];
  sourceType?: ClientResponseSourceType;
  /** Примітки */
  notes?: string;
  statistics?: ClientStatistics;
  /** Дата створення */
  readonly createdAt: string;
  /** Дата останнього оновлення */
  readonly updatedAt?: string;
}
