/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

export type ClientSearchRequestSourceType = typeof ClientSearchRequestSourceType[keyof typeof ClientSearchRequestSourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientSearchRequestSourceType = {
  REFERRAL: 'REFERRAL',
  ADVERTISING: 'ADVERTISING',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  WEBSITE: 'WEBSITE',
  WALKING_BY: 'WALKING_BY',
  REPEAT_CUSTOMER: 'REPEAT_CUSTOMER',
  OTHER: 'OTHER',
} as const;
