/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

export interface ClientStatistics {
  /** Загальна кількість замовлень */
  totalOrders?: number;
  /**
   * Грошова сума (в гривнях)
   * @minimum 0
   */
  totalSpent?: number;
  /** Дата в ISO 8601 форматі */
  lastOrderDate?: string;
  /**
   * Грошова сума (в гривнях)
   * @minimum 0
   */
  averageOrderValue?: number;
  /** Чи є клієнт VIP */
  isVip?: boolean;
  /** Дата в ISO 8601 форматі */
  registrationDate?: string;
}
