/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

export interface ErrorResponse {
  /** Час виникнення помилки */
  timestamp: string;
  /** HTTP статус код */
  status: number;
  /** Тип помилки */
  error: string;
  /** Опис помилки */
  message: string;
  /** Шлях запиту */
  path: string;
  /** Ідентифікатор для відстеження помилки */
  traceId?: string;
}
