/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { JsonNullableObject } from './jsonNullableObject';

export interface FieldError {
  /** Назва поля з помилкою */
  field: string;
  /** Опис помилки */
  message: string;
  /** Відхилене значення */
  rejectedValue?: JsonNullableObject;
  /** Код помилки валідації */
  code?: string;
}
