/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

export type GetClientsParams = {
/**
 * Номер сторінки (починається з 0)
 * @minimum 0
 */
page?: number;
/**
 * Розмір сторінки
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * Поле для сортування
 */
sort?: string;
};
