/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

export type SearchClientsParams = {
/**
 * Пошуковий запит (ім'я, прізвище, телефон, email)
 * @minLength 2
 * @maxLength 100
 */
query: string;
/**
 * Максимальна кількість результатів (для автозаповнення)
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
