/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateClientContactsRequestCommunicationMethodsItem } from './updateClientContactsRequestCommunicationMethodsItem';
import type { UpdateAddressRequest } from './updateAddressRequest';

export interface UpdateClientContactsRequest {
  /**
   * Номер телефону
   * @pattern ^\+380\d{9}$
   */
  phone?: string;
  /**
   * Email адреса
   * @minLength 0
   * @maxLength 254
   */
  email?: string;
  /** Бажані способи зв'язку */
  communicationMethods?: UpdateClientContactsRequestCommunicationMethodsItem[];
  address?: UpdateAddressRequest;
}
