openapi: 3.0.3
info:
  title: Aksi Dry Cleaning - Branch API
  description: API для управління філіями хімчистки
  version: 1.0.0

tags:
  - name: branches
    description: Управління філіями

paths:
  /branches:
    post:
      tags:
        - branches
      summary: Створення нової філії
      operationId: createBranch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBranchRequest"
      responses:
        '201':
          description: Філію успішно створено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchDTO"
        '400':
          description: Некоректні дані філії
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - branches
      summary: Отримання всіх філій
      operationId: getAllBranches
      parameters:
        - name: active
          in: query
          description: Фільтр за статусом (активні/неактивні)
          schema:
            type: boolean
        - name: page
          in: query
          description: Номер сторінки, починаючи з 0
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Розмір сторінки
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          description: Поле та напрямок сортування, наприклад name,asc
          schema:
            type: string
      responses:
        '200':
          description: Успішне отримання списку філій
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageBranchDTO"

  /branches/{id}:
    get:
      tags:
        - branches
      summary: Отримання філії за ID
      operationId: getBranchById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішне отримання філії
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchDTO"
        '404':
          description: Філію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags:
        - branches
      summary: Оновлення філії
      operationId: updateBranch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBranchRequest"
      responses:
        '200':
          description: Успішне оновлення філії
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchDTO"
        '404':
          description: Філію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '400':
          description: Некоректні дані філії
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - branches
      summary: Видалення філії
      operationId: deleteBranch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Успішне видалення філії
        '404':
          description: Філію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Філія використовується і не може бути видалена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /branches/{id}/activate:
    post:
      tags:
        - branches
      summary: Активація філії
      operationId: activateBranch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішна активація філії
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchDTO"
        '404':
          description: Філію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /branches/{id}/deactivate:
    post:
      tags:
        - branches
      summary: Деактивація філії
      operationId: deactivateBranch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішна деактивація філії
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchDTO"
        '404':
          description: Філію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /branches/{id}/employees:
    get:
      tags:
        - branches
      summary: Отримання співробітників філії
      operationId: getBranchEmployees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: active
          in: query
          description: Фільтр за статусом (активні/неактивні)
          schema:
            type: boolean
      responses:
        '200':
          description: Успішне отримання співробітників філії
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EmployeeDTO"
        '404':
          description: Філію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /branches/search:
    post:
      tags:
        - branches
      summary: Пошук філій за різними критеріями
      operationId: searchBranches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BranchSearchRequest"
      responses:
        '200':
          description: Успішний пошук філій
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageBranchDTO"

components:
  schemas:
    BranchDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          description: Назва філії
        code:
          type: string
          description: Унікальний код філії
        address:
          type: string
          description: Адреса філії
        city:
          type: string
          description: Місто розташування
        phone:
          type: string
          description: Контактний телефон
        email:
          type: string
          format: email
          description: Електронна пошта
        workingHours:
          type: string
          description: "Робочий час філії (наприклад, 'Пн-Пт: 9:00-19:00, Сб: 10:00-16:00')"
        managerId:
          type: integer
          format: int64
          description: ID керівника філії
        managerName:
          type: string
          description: Ім'я та прізвище керівника
        employeesCount:
          type: integer
          description: Кількість працівників філії
        active:
          type: boolean
          description: Чи активна філія
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - code
        - address
        - city
        - active
        - createdAt

    CreateBranchRequest:
      type: object
      properties:
        name:
          type: string
          description: Назва філії
          minLength: 1
          maxLength: 100
        code:
          type: string
          description: Унікальний код філії
          minLength: 1
          maxLength: 20
        address:
          type: string
          description: Адреса філії
          minLength: 1
          maxLength: 200
        city:
          type: string
          description: Місто розташування
          minLength: 1
          maxLength: 100
        phone:
          type: string
          description: Контактний телефон
          pattern: "^\\+?[0-9\\s\\-\\(\\)]+$"
        email:
          type: string
          format: email
          description: Електронна пошта
        workingHours:
          type: string
          description: Робочий час філії
        managerId:
          type: integer
          format: int64
          description: ID керівника філії
        active:
          type: boolean
          description: Чи активна філія
          default: true
      required:
        - name
        - code
        - address
        - city
        - phone

    UpdateBranchRequest:
      type: object
      properties:
        name:
          type: string
          description: Оновлена назва філії
          minLength: 1
          maxLength: 100
        address:
          type: string
          description: Оновлена адреса філії
          minLength: 1
          maxLength: 200
        city:
          type: string
          description: Оновлене місто розташування
          minLength: 1
          maxLength: 100
        phone:
          type: string
          description: Оновлений контактний телефон
          pattern: "^\\+?[0-9\\s\\-\\(\\)]+$"
        email:
          type: string
          format: email
          description: Оновлена електронна пошта
        workingHours:
          type: string
          description: Оновлений робочий час філії
        managerId:
          type: integer
          format: int64
          description: ID нового керівника філії

    BranchSearchRequest:
      type: object
      properties:
        name:
          type: string
          description: Частина назви для пошуку
        code:
          type: string
          description: Код філії для пошуку
        city:
          type: string
          description: Місто для фільтрації
        active:
          type: boolean
          description: Фільтр за статусом (активні/неактивні)
        page:
          type: integer
          default: 0
          description: Номер сторінки
        size:
          type: integer
          default: 20
          description: Розмір сторінки
        sort:
          type: string
          description: Поле та напрямок сортування
          default: "name,asc"

    EmployeeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
          description: ID користувача в системі
        firstName:
          type: string
        lastName:
          type: string
        position:
          type: string
          description: Посада співробітника
        phone:
          type: string
        email:
          type: string
          format: email
        branchId:
          type: integer
          format: int64
        branchName:
          type: string
        active:
          type: boolean
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - userId
        - firstName
        - lastName
        - position
        - branchId
        - active

    PageBranchDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/BranchDTO"
        pageable:
          type: object
          properties:
            pageNumber:
              type: integer
            pageSize:
              type: integer
            sort:
              type: object
              properties:
                empty:
                  type: boolean
                sorted:
                  type: boolean
                unsorted:
                  type: boolean
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        last:
          type: boolean
        size:
          type: integer
        number:
          type: integer
        sort:
          type: object
          properties:
            empty:
              type: boolean
            sorted:
              type: boolean
            unsorted:
              type: boolean
        numberOfElements:
          type: integer
        first:
          type: boolean
        empty:
          type: boolean
      required:
        - content
        - totalElements
        - totalPages

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - timestamp
        - status
        - error
        - message
        - path
