openapi: 3.0.3
info:
  title: Aksi Dry Cleaning - Item API
  description: API для управління типами предметів та категоріями у системі хімчистки
  version: 1.0.0

tags:
  - name: item-types
    description: Управління типами предметів
  - name: categories
    description: Управління категоріями предметів

paths:
  /item-types:
    post:
      tags:
        - item-types
      summary: Створення нового типу предмету
      operationId: createItemType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateItemTypeRequest"
      responses:
        '201':
          description: Тип предмету успішно створено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemTypeDTO"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - item-types
      summary: Отримання всіх типів предметів з пагінацією
      operationId: getAllItemTypes
      parameters:
        - name: page
          in: query
          description: Номер сторінки
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Розмір сторінки
          schema:
            type: integer
            default: 50
        - name: sort
          in: query
          description: Поле та напрямок сортування
          schema:
            type: string
            default: "name,asc"
      responses:
        '200':
          description: Успішне отримання списку типів предметів
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageItemTypeDTO"
  
  /item-types/{id}:
    get:
      tags:
        - item-types
      summary: Отримання типу предмету за ID
      operationId: getItemTypeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішне отримання типу предмету
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemTypeDTO"
        '404':
          description: Тип предмету не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags:
        - item-types
      summary: Оновлення типу предмету
      operationId: updateItemType
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateItemTypeRequest"
      responses:
        '200':
          description: Успішне оновлення типу предмету
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemTypeDTO"
        '404':
          description: Тип предмету не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - item-types
      summary: Видалення типу предмету
      operationId: deleteItemType
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Успішне видалення типу предмету
        '404':
          description: Тип предмету не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Тип предмету використовується і не може бути видалений
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  
  /item-types/search:
    post:
      tags:
        - item-types
      summary: Пошук типів предметів
      operationId: searchItemTypes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemTypeSearchRequest"
      responses:
        '200':
          description: Успішний пошук типів предметів
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageItemTypeDTO"
  
  /item-types/by-category/{categoryId}:
    get:
      tags:
        - item-types
      summary: Отримання типів предметів за категорією
      operationId: getItemTypesByCategory
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішне отримання типів предметів
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ItemTypeDTO"
        '404':
          description: Категорію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /categories:
    post:
      tags:
        - categories
      summary: Створення нової категорії
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategoryRequest"
      responses:
        '201':
          description: Категорію успішно створено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryDTO"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - categories
      summary: Отримання всіх категорій
      operationId: getAllCategories
      responses:
        '200':
          description: Успішне отримання списку категорій
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryDTO"
  
  /categories/{id}:
    get:
      tags:
        - categories
      summary: Отримання категорії за ID
      operationId: getCategoryById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішне отримання категорії
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryDTO"
        '404':
          description: Категорію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags:
        - categories
      summary: Оновлення категорії
      operationId: updateCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCategoryRequest"
      responses:
        '200':
          description: Успішне оновлення категорії
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryDTO"
        '404':
          description: Категорію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - categories
      summary: Видалення категорії
      operationId: deleteCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Успішне видалення категорії
        '404':
          description: Категорію не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Категорія використовується і не може бути видалена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ItemTypeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          description: Назва типу предмету
        code:
          type: string
          description: Унікальний код типу предмету
        basePrice:
          type: number
          format: double
          description: Базова ціна
        categoryId:
          type: integer
          format: int64
          description: ID категорії
        categoryName:
          type: string
          description: Назва категорії
        description:
          type: string
          description: Опис типу предмету
        availableModifiers:
          type: array
          items:
            $ref: "#/components/schemas/ModifierReferenceDTO"
          description: Доступні модифікатори
        supportsExpedite:
          type: boolean
          description: Чи підтримує терміновість
        active:
          type: boolean
          description: Чи активний тип предмету
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - code
        - basePrice
        - categoryId
        - supportsExpedite
        - active

    CreateItemTypeRequest:
      type: object
      properties:
        name:
          type: string
          description: Назва типу предмету
          minLength: 1
          maxLength: 100
        code:
          type: string
          description: Унікальний код типу предмету
          minLength: 1
          maxLength: 50
        basePrice:
          type: number
          format: double
          description: Базова ціна
          minimum: 0
        categoryId:
          type: integer
          format: int64
          description: ID категорії
        description:
          type: string
          description: Опис типу предмету
        availableModifierIds:
          type: array
          items:
            type: integer
            format: int64
          description: ID доступних модифікаторів
        supportsExpedite:
          type: boolean
          description: Чи підтримує терміновість
          default: true
        active:
          type: boolean
          description: Чи активний тип предмету
          default: true
      required:
        - name
        - code
        - basePrice
        - categoryId

    UpdateItemTypeRequest:
      type: object
      properties:
        name:
          type: string
          description: Назва типу предмету
          minLength: 1
          maxLength: 100
        basePrice:
          type: number
          format: double
          description: Базова ціна
          minimum: 0
        categoryId:
          type: integer
          format: int64
          description: ID категорії
        description:
          type: string
          description: Опис типу предмету
        availableModifierIds:
          type: array
          items:
            type: integer
            format: int64
          description: ID доступних модифікаторів
        supportsExpedite:
          type: boolean
          description: Чи підтримує терміновість
        active:
          type: boolean
          description: Чи активний тип предмету

    ItemTypeSearchRequest:
      type: object
      properties:
        name:
          type: string
          description: Частина назви для пошуку
        code:
          type: string
          description: Код для пошуку
        categoryId:
          type: integer
          format: int64
          description: ID категорії для фільтрації
        activeOnly:
          type: boolean
          description: Фільтрувати лише активні
          default: true
        page:
          type: integer
          description: Номер сторінки
          default: 0
        size:
          type: integer
          description: Розмір сторінки
          default: 20
        sort:
          type: string
          description: Поле та напрямок сортування
          default: "name,asc"

    CategoryDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          description: Назва категорії
        code:
          type: string
          description: Унікальний код категорії
        description:
          type: string
          description: Опис категорії
        itemTypesCount:
          type: integer
          description: Кількість типів предметів у категорії
        active:
          type: boolean
          description: Чи активна категорія
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - code
        - active

    CreateCategoryRequest:
      type: object
      properties:
        name:
          type: string
          description: Назва категорії
          minLength: 1
          maxLength: 100
        code:
          type: string
          description: Унікальний код категорії
          minLength: 1
          maxLength: 50
        description:
          type: string
          description: Опис категорії
        active:
          type: boolean
          description: Чи активна категорія
          default: true
      required:
        - name
        - code

    UpdateCategoryRequest:
      type: object
      properties:
        name:
          type: string
          description: Назва категорії
          minLength: 1
          maxLength: 100
        description:
          type: string
          description: Опис категорії
        active:
          type: boolean
          description: Чи активна категорія

    ModifierReferenceDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
          enum:
            - PERCENTAGE
            - FIXED
            - COLOR
            - FIXED_QUANTITY
            - RANGE_PERCENTAGE
        defaultValue:
          type: number
          format: double
      required:
        - id
        - name
        - type

    PageItemTypeDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/ItemTypeDTO"
        pageable:
          $ref: "#/components/schemas/PageableDTO"
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        last:
          type: boolean
        size:
          type: integer
        number:
          type: integer
        sort:
          $ref: "#/components/schemas/SortDTO"
        numberOfElements:
          type: integer
        first:
          type: boolean
        empty:
          type: boolean
      required:
        - content
        - totalElements
        - totalPages

    PageableDTO:
      type: object
      properties:
        pageNumber:
          type: integer
        pageSize:
          type: integer
        sort:
          $ref: "#/components/schemas/SortDTO"

    SortDTO:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - timestamp
        - status
        - error
        - message
        - path
