openapi: 3.0.3
info:
  title: Aksi Dry Cleaning - Order API
  description: API для управління замовленнями хімчистки
  version: 1.0.0

tags:
  - name: orders
    description: Управління замовленнями

paths:
  /orders:
    post:
      tags:
        - orders
      summary: Створення нового замовлення
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
      responses:
        '201':
          description: Замовлення успішно створене
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDTO"
        '400':
          description: Некоректні дані замовлення
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - orders
      summary: Отримання всіх замовлень із пагінацією
      operationId: getAllOrders
      parameters:
        - name: page
          in: query
          description: Номер сторінки, починаючи з 0
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Розмір сторінки
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          description: Поле та напрямок сортування, наприклад createdAt,desc
          schema:
            type: string
      responses:
        '200':
          description: Успішне отримання списку замовлень
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOrderDTO"

  /orders/{id}:
    get:
      tags:
        - orders
      summary: Отримання замовлення за ID
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішне отримання замовлення
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDTO"
        '404':
          description: Замовлення не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags:
        - orders
      summary: Оновлення замовлення
      operationId: updateOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderRequest"
      responses:
        '200':
          description: Успішне оновлення замовлення
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDTO"
        '404':
          description: Замовлення не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '400':
          description: Некоректні дані замовлення
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - orders
      summary: Видалення замовлення
      operationId: deleteOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Успішне видалення замовлення
        '404':
          description: Замовлення не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /orders/search:
    post:
      tags:
        - orders
      summary: Пошук замовлень за різними критеріями
      operationId: searchOrders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderSearchRequest"
      responses:
        '200':
          description: Успішний пошук замовлень
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOrderDTO"

components:
  schemas:
    OrderStatus:
      type: string
      enum:
        - CREATED
        - IN_PROGRESS
        - READY
        - COMPLETED
        - CANCELLED
      description: Статус замовлення

    PaymentMethod:
      type: string
      enum:
        - CASH
        - CARD
        - BANK_TRANSFER
      description: Спосіб оплати

    DiscountType:
      type: string
      enum:
        - NONE
        - EVERCARD
        - SOCIAL_MEDIA
        - MILITARY
        - CUSTOM
      description: Тип знижки

    ExpediteOption:
      type: string
      enum:
        - REGULAR
        - EXPEDITED_50
        - EXPEDITED_100
      description: Опція терміновості

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - timestamp
        - status
        - error
        - message
        - path
