openapi: 3.0.3
info:
  title: Aksi Dry Cleaning - Pricing API
  description: API для управління системою ціноутворення
  version: 1.0.0

tags:
  - name: price-modifiers
    description: Управління модифікаторами ціни
  - name: price-list
    description: Управління прайс-листами

paths:
  /price-modifiers:
    post:
      tags:
        - price-modifiers
      summary: Створення нового модифікатора ціни
      operationId: createPriceModifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePriceModifierRequest"
      responses:
        '201':
          description: Модифікатор ціни успішно створено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceModifierDTO"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - price-modifiers
      summary: Отримання всіх модифікаторів ціни
      operationId: getAllPriceModifiers
      parameters:
        - name: type
          in: query
          description: Тип модифікатора для фільтрації
          schema:
            $ref: "#/components/schemas/ModifierType"
        - name: active
          in: query
          description: Фільтр за активністю
          schema:
            type: boolean
      responses:
        '200':
          description: Успішне отримання списку модифікаторів
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PriceModifierDTO"

  /price-modifiers/{id}:
    get:
      tags:
        - price-modifiers
      summary: Отримання модифікатора за ID
      operationId: getPriceModifierById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішне отримання модифікатора
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceModifierDTO"
        '404':
          description: Модифікатор не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags:
        - price-modifiers
      summary: Оновлення модифікатора ціни
      operationId: updatePriceModifier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePriceModifierRequest"
      responses:
        '200':
          description: Успішне оновлення модифікатора
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceModifierDTO"
        '404':
          description: Модифікатор не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - price-modifiers
      summary: Видалення модифікатора ціни
      operationId: deletePriceModifier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Успішне видалення модифікатора
        '404':
          description: Модифікатор не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Модифікатор використовується і не може бути видалений
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /price-modifiers/search:
    post:
      tags:
        - price-modifiers
      summary: Пошук модифікаторів ціни
      operationId: searchPriceModifiers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PriceModifierSearchRequest"
      responses:
        '200':
          description: Успішний пошук модифікаторів
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagePriceModifierDTO"

  /price-list:
    post:
      tags:
        - price-list
      summary: Створення нового прайс-листа
      operationId: createPriceList
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePriceListRequest"
      responses:
        '201':
          description: Прайс-лист успішно створено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceListDTO"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - price-list
      summary: Отримання всіх прайс-листів
      operationId: getAllPriceLists
      parameters:
        - name: active
          in: query
          description: Фільтр за активністю
          schema:
            type: boolean
      responses:
        '200':
          description: Успішне отримання списку прайс-листів
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PriceListDTO"

  /price-list/{id}:
    get:
      tags:
        - price-list
      summary: Отримання прайс-листа за ID
      operationId: getPriceListById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішне отримання прайс-листа
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceListDTO"
        '404':
          description: Прайс-лист не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags:
        - price-list
      summary: Оновлення прайс-листа
      operationId: updatePriceList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePriceListRequest"
      responses:
        '200':
          description: Успішне оновлення прайс-листа
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceListDTO"
        '404':
          description: Прайс-лист не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - price-list
      summary: Видалення прайс-листа
      operationId: deletePriceList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Успішне видалення прайс-листа
        '404':
          description: Прайс-лист не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Прайс-лист використовується і не може бути видалений
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /price-list/active:
    get:
      tags:
        - price-list
      summary: Отримання активного прайс-листа
      operationId: getActivePriceList
      responses:
        '200':
          description: Успішне отримання активного прайс-листа
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceListDTO"
        '404':
          description: Активний прайс-лист не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /price-list/{id}/activate:
    post:
      tags:
        - price-list
      summary: Активація прайс-листа
      operationId: activatePriceList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішна активація прайс-листа
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceListDTO"
        '404':
          description: Прайс-лист не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /price-list/{id}/items:
    get:
      tags:
        - price-list
      summary: Отримання всіх позицій прайс-листа
      operationId: getPriceListItems
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: categoryId
          in: query
          description: Фільтр за категорією
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успішне отримання позицій прайс-листа
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PriceListItemDTO"
        '404':
          description: Прайс-лист не знайдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /price-calculation/estimate-item:
    post:
      tags:
        - price-list
      summary: Розрахунок ціни для позиції замовлення
      operationId: calculateItemPrice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemPriceCalculationRequest"
      responses:
        '200':
          description: Успішний розрахунок ціни
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemPriceCalculationResult"
        '400':
          description: Некоректні дані
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Предмет не знайдено в прайс-листі
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ModifierType:
      type: string
      enum:
        - PERCENTAGE
        - FIXED
        - COLOR
        - FIXED_QUANTITY
        - RANGE_PERCENTAGE
      description: Тип модифікатора ціни

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - timestamp
        - status
        - error
        - message
        - path
