spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:aksi-postgres}:${DB_PORT:5432}/${DB_NAME:aksi_cleaners_db_v5}?schema=public
    username: ${DB_USERNAME:aksi_user}
    password: ${DB_PASSWORD:1911}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework: WARN
    com.aksi: INFO
