spring:
  application:
    name: aksi-backend
  profiles:
    include: files
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: aksi.vn.ua@gmail.com
    password: ${MAIL_PASSWORD:your_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    contexts: default
    clear-checksums: true
    parameters:
      create-uuid-extension: CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  datasource:
    url: jdbc:postgresql://postgres:5432/aksi_cleaners_db_v5
    username: aksi_user
    password: 1911
    driver-class-name: org.postgresql.Driver
    schema: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Діалект PostgreSQL автоматично визначається Hibernate
        hbm2ddl:
          auto: validate
    open-in-view: false
    # Видалено налаштування автоматичної генерації схеми
    # Вимкнено globally_quoted_identifiers, бо це може спричиняти проблеми з валідацією
  web:
    cors:
      allowed-origins: 'http://localhost:3000,http://127.0.0.1:3000'
      allowed-methods: 'GET,POST,PUT,DELETE,OPTIONS,PATCH'
      allowed-headers: '*'
      allow-credentials: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Налаштування JWT
jwt:
  secret: 7Jl7CMvDgZaYWEr3ZsRMRi1CJG3vjYXm0QFrDHB3z1WGMhsQ+yWgYMwzM6MqkVEM3J40TxOFsYyyvmFkh76WDQ==
  expiration: 86400000 # 24 години у мілісекундах
  refresh:
    expiration: 604800000 # 7 днів у мілісекундах

# Налаштування адміністратора за замовчуванням
admin:
  username: admin
  password: Aksi1911
  email: admin@aksi.com

# Налаштування Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
    logfile:
      enabled: true
      path: logs/aksi-app.log
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.aksi: DEBUG
    # Розширені налаштування для логування Swagger/OpenAPI
    # springdoc: TRACE
    # org.springdoc: TRACE
    # io.swagger.v3: TRACE
    com.aksi.config: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
  file:
    name: logs/aksi-app.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %cyan(%logger{15}) - %msg%n'

# Налаштування OpenAPI/Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    filter: true
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: -1
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.aksi.api
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**
  cache:
    disabled: true
