server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: dry-cleaning-order-system

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aksi_cleaners_db_v5}
    username: ${SPRING_DATASOURCE_USERNAME:aksi_user}
    password: ${SPRING_DATASOURCE_PASSWORD:1911}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  # DevTools configuration for hot reload
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
      port: 35729

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  info:
    title: AKSI Dry Cleaning Order System API
    description: API для односторінкової системи замовлень хімчистки з DDD архітектурою
    version: 1.0.0
    contact:
      name: AKSI Development Team

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.aksi: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

# Custom application properties
aksi:
  order:
    receipt:
      number:
        prefix: "AKSI-"
        length: 8
    photo:
      max-size-mb: 5
      max-count-per-item: 5
      upload-path: "uploads/photos/"
  pdf:
    output-path: "uploads/receipts/"
  qr:
    base-url: "https://aksi.com.ua/track/"

# JWT Configuration
jwt:
  secret: 7Jl7CMvDgZaYWEr3ZsRMRi1CJG3vjYXm0QFrDHB3z1WGMhsQ+yWgYMwzM6MqkVEM3J40TxOFsYyyvmFkh76WDQ==
  expiration: 86400000 # 24 години у мілісекундах
  refresh:
    expiration: 604800000 # 7 днів у мілісекундах

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/aksi_cleaners_db_v5}
    username: ${SPRING_DATASOURCE_USERNAME:aksi_user}
    password: ${SPRING_DATASOURCE_PASSWORD:1911}

  jpa:
    hibernate:
      ddl-auto: update # Для dev - дозволяємо Hibernate оновлювати схему
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Liquibase для dev - стабільна схема
  liquibase:
    enabled: true # Liquibase увімкнений але без drop-first
    # drop-first: true # ВІДКЛЮЧЕНО: призводить до постійних recreate при DevTools restart

  # Disable mail health check in dev
  mail:
    test-connection: false

# Actuator для dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# МАКСИМАЛЬНО ЧИСТІ ЛОГИ - тільки критичні повідомлення
logging:
  level:
    root: ERROR # Тільки помилки для всього
    com.aksi: ${AKSI_LOG_LEVEL:WARN} # Наш код - керується змінною оточення
    org.springframework: ERROR # Весь Spring - тільки помилки
    org.hibernate: ERROR # Hibernate - тільки помилки
    liquibase: ERROR # Liquibase - тільки помилки
    org.postgresql: ERROR # PostgreSQL - тільки помилки
    org.postgresql.Driver: ERROR # PostgreSQL Driver
    com.zaxxer.hikari: ERROR # HikariCP connection pool
    org.apache.maven: ERROR # Maven - тільки помилки
    org.openapitools: ERROR # OpenAPI генератор - тільки помилки
    # Критично важливі логи для діагностики
    org.springframework.boot.actuator.health: WARN
    org.springframework.boot.web.embedded.tomcat: WARN # Tomcat startup
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
