spring:
  profiles:
    active: dev  # Default profile
  application:
    name: AKSI-Dry-Cleaning-Backend
    
# Base configuration that applies to all profiles
server:
  error:
    include-message: always
    include-binding-errors: always

# CORS configuration
app:
  cors:
    allowed-origins: http://localhost:3000