spring:
  profiles:
    active: dev # Default profile
  application:
    name: AKSI-Dry-Cleaning-Backend
  # Force English locale for validation messages
  web:
    locale: en_US
    locale-resolver: fixed
  # Messages configuration
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

# Base configuration that applies to all profiles
server:
  error:
    include-message: always
    include-binding-errors: always

# Logging configuration
logging:
  level:
    com.aksi: DEBUG
    org.springframework.security: DEBUG
    SECURITY_AUDIT: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application configuration
app:
  cors:
    allowed-origins: http://localhost:3000

  # File storage configuration (default values - can be overridden in profiles)
  file-storage:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    base-url: ${FILE_BASE_URL:http://localhost:8080}
    api-path: ${FILE_API_PATH:/api/files}

  # Security configuration (default values - override in profiles)
  security:
    # Rate limiting settings
    rate-limiting:
      enabled: false # Disabled by default for development
    max-attempts-per-user: 999 # Very high for development
    max-attempts-per-ip: 999 # Very high for development
    lockout-duration-minutes: 1 # Short lockout for development
    attempt-window-minutes: 60

    # Password policy settings (relaxed for development)
    password:
      min-length: 6 # Short for development
      require-uppercase: false
      require-lowercase: false
      require-numbers: false
      require-special-chars: false
      allowed-special-chars: "@$!%*?&"

    # Session management settings
    session:
      default-timeout-minutes: 480 # 8 hours for development
      max-concurrent-sessions: 10 # Many sessions for testing
      remember-me-timeout-days: 30
      session-fixation-protection: true

# Receipt configuration
receipt:
  default-branch-name: "AKSI"
  default-payment-method: "CASH"
  currency: "грн"
  phone-prefix: "Тел: "
  date-time-format: "dd.MM.yyyy HH:mm"
  date-format: "dd.MM.yyyy"

  font:
    directory: "fonts/"
    regular: "DejaVuSans.ttf"
    bold: "DejaVuSans-Bold.ttf"
    title-size: 18
    heading-size: 12
    normal-size: 10
    small-size: 8

  layout:
    page-width: 595.0
    page-height: 842.0
    margin-top: 50.0
    margin-bottom: 50.0
    margin-left: 50.0
    margin-right: 50.0
    table-width: 495.0
    item-table-column-widths: [280.0, 45.0, 85.0, 85.0]
    line-spacing: 15.0
    section-spacing: 20.0
    cell-padding: 5.0
    content-start-y: 792.0
    content-end-y: 50.0
