spring:
  datasource:
    url: jdbc:postgresql://aksi-postgres:5432/aksi_cleaners_db_v5?schema=public
    username: aksi_user
    password: 1911
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.springframework.web: WARN
    com.aksi: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.aksi.config: WARN
    org.springframework.security: WARN
    org.springframework.boot: WARN
    org.springframework.boot.autoconfigure: WARN
    com.zaxxer.hikari: WARN
    liquibase: WARN
