/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

export interface ClientSearchResult {
  /** Унікальний ідентифікатор (UUID v4) */
  id?: string;
  firstName?: string;
  lastName?: string;
  readonly fullName?: string;
  phone?: string;
  email?: string;
  /** Дата в ISO 8601 форматі */
  lastOrderDate?: string;
  /** Кількість замовлень */
  orderCount?: number;
  /** Поля, які відповідають пошуковому запиту */
  highlightedFields?: string[];
}
