/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAddressRequest } from './updateAddressRequest';
import type { UpdateClientRequestCommunicationMethodsItem } from './updateClientRequestCommunicationMethodsItem';
import type { UpdateClientRequestSourceType } from './updateClientRequestSourceType';

export interface UpdateClientRequest {
  /**
   * Ім'я клієнта
   * @minLength 2
   * @maxLength 50
   */
  firstName?: string;
  /**
   * Прізвище клієнта
   * @minLength 2
   * @maxLength 50
   */
  lastName?: string;
  /**
   * Номер телефону в міжнародному форматі
   * @pattern ^\+380\d{9}$
   */
  phone?: string;
  /**
   * Email адреса
   * @minLength 0
   * @maxLength 254
   */
  email?: string;
  address?: UpdateAddressRequest;
  /** Бажані способи зв'язку */
  communicationMethods?: UpdateClientRequestCommunicationMethodsItem[];
  sourceType?: UpdateClientRequestSourceType;
  /**
   * Додаткові примітки про клієнта
   * @minLength 0
   * @maxLength 500
   */
  notes?: string;
}
