openapi: 3.0.4
info:
  title: Branch API
  description: Branch management API for dry cleaning service
  version: 1.0.0
  contact:
    name: API Support
    email: support@dryclean.example.com

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.dryclean.example.com
    description: Production

tags:
  - name: branches
    description: Branch management operations

paths:
  # Branch endpoints
  /api/branches:
    $ref: "./paths/branch-paths.yaml#/paths/~1api~1branches"
  /api/branches/active:
    $ref: "./paths/branch-paths.yaml#/paths/~1api~1branches~1active"
  /api/branches/{branchId}:
    $ref: "./paths/branch-paths.yaml#/paths/~1api~1branches~1{branchId}"
  /api/branches/{branchId}/activate:
    $ref: "./paths/branch-paths.yaml#/paths/~1api~1branches~1{branchId}~1activate"
  /api/branches/{branchId}/deactivate:
    $ref: "./paths/branch-paths.yaml#/paths/~1api~1branches~1{branchId}~1deactivate"

components:
  responses:
    BadRequest:
      $ref: "../common.yaml#/components/responses/BadRequest"
    Unauthorized:
      $ref: "../common.yaml#/components/responses/Unauthorized"
    Forbidden:
      $ref: "../common.yaml#/components/responses/Forbidden"
    NotFound:
      $ref: "../common.yaml#/components/responses/NotFound"
    Conflict:
      $ref: "../common.yaml#/components/responses/Conflict"

  parameters:
    PageNumber:
      $ref: "../common.yaml#/components/parameters/PageNumber"
    PageSize:
      $ref: "../common.yaml#/components/parameters/PageSize"
    SortBy:
      $ref: "../common.yaml#/components/parameters/SortBy"
    SortOrder:
      $ref: "../common.yaml#/components/parameters/SortOrder"

  schemas:
    # Import all schemas from branch-schemas.yaml
    BranchInfo:
      $ref: "./schemas/branch-schemas.yaml#/components/schemas/BranchInfo"
    CreateBranchRequest:
      $ref: "./schemas/branch-schemas.yaml#/components/schemas/CreateBranchRequest"
    UpdateBranchRequest:
      $ref: "./schemas/branch-schemas.yaml#/components/schemas/UpdateBranchRequest"
    BranchListResponse:
      $ref: "./schemas/branch-schemas.yaml#/components/schemas/BranchListResponse"

    # Common schemas (if needed locally)
    PaginatedResponse:
      $ref: "../common.yaml#/components/schemas/PaginatedResponse"
    UniqueName:
      $ref: "../common.yaml#/components/schemas/UniqueName"
    PhoneNumber:
      $ref: "../common.yaml#/components/schemas/PhoneNumber"
    Email:
      $ref: "../common.yaml#/components/schemas/Email"

security:
  - cookieAuth: []
