name: Update README versions

permissions:
  contents: write

on:
  schedule:
    - cron: "0 6 * * 1" # Every Monday 06:00 UTC
  push:
    paths:
      - "backend/pom.xml"
      - "frontend/package.json"
      - "README.md" # allow manual tweak to retrigger
      - "scripts/update-readme-versions.js"
  workflow_dispatch: {}

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update README placeholders
        run: |
          cd $GITHUB_WORKSPACE
          node scripts/update-readme-versions.js || true

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(docs): auto-update README version badges"
            git push
          else
            echo "No changes to commit"
          fi
