/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

export type ClientContactsResponseCommunicationMethodsItem = typeof ClientContactsResponseCommunicationMethodsItem[keyof typeof ClientContactsResponseCommunicationMethodsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientContactsResponseCommunicationMethodsItem = {
  PHONE: 'PHONE',
  SMS: 'SMS',
  VIBER: 'VIBER',
  TELEGRAM: 'TELEGRAM',
  EMAIL: 'EMAIL',
} as const;
