/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { ClientResponse } from './clientResponse';
import type { PageableInfo } from './pageableInfo';

export interface ClientPageResponse {
  content?: ClientResponse[];
  pageable?: PageableInfo;
  /** Загальна кількість елементів */
  totalElements?: number;
  /** Загальна кількість сторінок */
  totalPages?: number;
  /** Чи це остання сторінка */
  last?: boolean;
  /** Чи це перша сторінка */
  first?: boolean;
  /** Кількість елементів на поточній сторінці */
  numberOfElements?: number;
}
