/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { PageableInfoSort } from './pageableInfoSort';

export interface PageableInfo {
  /**
   * Номер поточної сторінки (починаючи з 0)
   * @minimum 0
   */
  page: number;
  /**
   * Розмір сторінки
   * @minimum 1
   */
  size: number;
  /** Загальна кількість елементів */
  totalElements: number;
  /** Загальна кількість сторінок */
  totalPages: number;
  /** Чи є поточна сторінка останньою */
  last: boolean;
  /** Чи є поточна сторінка першою */
  first: boolean;
  /** Кількість елементів на поточній сторінці */
  numberOfElements: number;
  sort?: PageableInfoSort;
}
