/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAddressRequest {
  /**
   * Вулиця та номер будинку
   * @minLength 0
   * @maxLength 200
   */
  street?: string;
  /**
   * Місто
   * @minLength 0
   * @maxLength 100
   */
  city?: string;
  /**
   * Область/регіон
   * @minLength 0
   * @maxLength 100
   */
  region?: string;
  /**
   * Поштовий індекс
   * @minLength 0
   * @maxLength 10
   */
  postalCode?: string;
  /**
   * Країна
   * @minLength 0
   * @maxLength 100
   */
  country?: string;
}
