/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * AKSI Dry Cleaning Order System API
 * API для односторінкової системи замовлень хімчистки з DDD архітектурою
 * OpenAPI spec version: 1.0.0
 */
import type { FieldError } from './fieldError';

export interface ValidationErrorResponse {
  /** Час виникнення помилки */
  timestamp: string;
  /** HTTP статус код (400) */
  status: number;
  /** Тип помилки */
  error: string;
  /** Загальний опис помилки валідації */
  message: string;
  /** Шлях запиту */
  path: string;
  /** Список помилок валідації полів */
  errors: FieldError[];
}
